import fs from "fs";
import path from "path";
import { PassThrough } from "stream";
import { fileURLToPath } from "url";
import PDFDocument from "pdfkit";
import { env } from "../config/env.js";
import { generateInvoiceNumber } from "../utils/invoice-number.js";
import { isObjectStorageEnabled, toPublicFileUrl, uploadBufferToStorage, writeBufferToFile } from "./storage-service.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const companyLogoPath = path.resolve(__dirname, "../public/invoice.png");
const invoiceDisclaimer =
  "This invoice is generated by ElevenOrbits for managed services and related account charges. Service delivery, provisioning, renewals, cancellations, and support remain subject to ElevenOrbits service terms and any active service agreement. Paid invoices confirm payment receipt only and do not transfer ownership of licensed software, third-party infrastructure, IP addresses, domains, or provider-managed resources. Taxes, duties, banking fees, currency conversion charges, and third-party processing fees remain the customer's responsibility unless explicitly stated otherwise.";

const palette = {
  page: "#f8fafc",
  card: "#ffffff",
  border: "#d7e1ec",
  header: "#0f172a",
  text: "#0f172a",
  muted: "#64748b",
  subtle: "#cbd5e1",
  tableHeader: "#e2e8f0",
};

export async function nextInvoiceNumber(InvoiceModel) {
  const count = await InvoiceModel.countDocuments();
  return generateInvoiceNumber(count + 1);
}

function formatMoney(amount, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency || "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Number(amount || 0));
}

function formatDate(value) {
  if (!value) {
    return "Pending";
  }

  return new Date(value).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function humanizeValue(value, fallback = "Not provided") {
  if (!value) {
    return fallback;
  }

  return String(value)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function formatBillingCycle(billingCycle) {
  if (!billingCycle) {
    return "Monthly";
  }

  const labels = {
    monthly: "Monthly",
    yearly: "Yearly",
    contact_sales: "Contact Sales",
  };

  return labels[billingCycle] || humanizeValue(billingCycle, "Monthly");
}

function formatPaymentMethodLabel(paymentMethodType, paymentReferenceCode) {
  let resolvedType = paymentMethodType || "";

  if (!resolvedType && String(paymentReferenceCode || "").startsWith("wallet_balance_")) {
    resolvedType = "wallet_balance";
  }

  const labels = {
    wallet_balance: "Wallet Balance",
    stripe_card: "Stripe Card",
    "wallet_balance + stripe_card": "Wallet Balance + Stripe Card",
    "wallet_balance + pending_card_payment": "Wallet Balance + Pending Card Payment",
    pending_confirmation: "Pending Customer Confirmation",
  };

  return labels[resolvedType] || humanizeValue(resolvedType, "Pending");
}

function formatAddress(customer) {
  const structuredAddress = [
    customer?.billingAddress?.line1,
    customer?.billingAddress?.line2,
    customer?.billingAddress?.city,
    customer?.billingAddress?.state,
    customer?.billingAddress?.postalCode,
    customer?.billingAddress?.country,
  ].filter(Boolean);

  if (structuredAddress.length) {
    return structuredAddress.join(", ");
  }

  if (customer?.address) {
    return String(customer.address);
  }

  return "Not provided";
}

function normalizeLineItems(invoice, planName) {
  const items =
    invoice?.lineItems?.length > 0
      ? invoice.lineItems
      : [
          {
            label: planName || "Managed Service",
            amount: invoice?.amount || 0,
            quantity: 1,
          },
        ];

  return items.map((item) => {
    const quantity = Math.max(Number(item.quantity || 1), 1);
    const amount = Number(item.amount || 0);

    return {
      label: item.label || planName || "Managed Service",
      quantity,
      amount,
      unitAmount: quantity > 0 ? amount / quantity : amount,
    };
  });
}

function drawOutlinedCard(doc, x, y, width, height) {
  doc.save();
  doc.fillColor(palette.card);
  doc.roundedRect(x, y, width, height, 16).fill();
  doc.strokeColor(palette.border).lineWidth(1);
  doc.roundedRect(x, y, width, height, 16).stroke();
  doc.restore();
}

function measureTextBlockHeight(doc, { text, width, font = "Helvetica", fontSize = 11 }) {
  doc.font(font).fontSize(fontSize);
  return doc.heightOfString(String(text || ""), { width });
}

function getKeyValueHeight(doc, { width, label, value }) {
  const labelHeight = measureTextBlockHeight(doc, {
    text: String(label || "").toUpperCase(),
    width,
    font: "Helvetica-Bold",
    fontSize: 9,
  });
  const valueHeight = measureTextBlockHeight(doc, {
    text: value,
    width,
    font: "Helvetica",
    fontSize: 11,
  });

  return labelHeight + 3 + valueHeight;
}

function getKeyValueGroupHeight(doc, { width, rows, gap = 10 }) {
  return rows.reduce((sum, [label, value], index) => {
    return sum + getKeyValueHeight(doc, { width, label, value }) + (index < rows.length - 1 ? gap : 0);
  }, 0);
}

function drawKeyValue(doc, { x, y, width, label, value }) {
  const labelText = String(label || "").toUpperCase();
  const valueText = String(value || "");

  doc.font("Helvetica-Bold").fontSize(9).fillColor(palette.muted).text(labelText, x, y, { width });
  const labelHeight = doc.heightOfString(labelText, { width });

  doc.font("Helvetica").fontSize(11).fillColor(palette.text).text(valueText, x, y + labelHeight + 3, { width });

  return getKeyValueHeight(doc, {
    width,
    label: labelText,
    value: valueText,
  });
}

function drawStatusBadge(doc, status, x, y) {
  const tone = {
    paid: { background: "#dcfce7", text: "#166534" },
    pending: { background: "#fef3c7", text: "#92400e" },
    rejected: { background: "#fee2e2", text: "#b91c1c" },
    void: { background: "#e2e8f0", text: "#475569" },
  }[status] || { background: "#e2e8f0", text: "#334155" };

  doc.save();
  doc.font("Helvetica-Bold").fontSize(10);
  const label = humanizeValue(status || "pending", "Pending");
  const badgeWidth = Math.max(doc.widthOfString(label) + 24, 84);

  doc.fillColor(tone.background);
  doc.roundedRect(x - badgeWidth, y, badgeWidth, 24, 12).fill();
  doc.fillColor(tone.text).text(label, x - badgeWidth, y + 7, {
    width: badgeWidth,
    align: "center",
  });
  doc.restore();
}

export async function generateInvoicePdf({ invoice, customer, planName, supportEmail }) {
  fs.mkdirSync(env.invoiceDir, { recursive: true });

  const fileName = `${invoice.invoiceNumber}.pdf`;
  const filePath = path.join(env.invoiceDir, fileName);
  const fileUrl = toPublicFileUrl(`/files/invoices/${fileName}`);
  const storageKey = `invoices/${fileName}`;

  const normalizedItems = normalizeLineItems(invoice, planName);
  const subtotal = normalizedItems.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const customerAddress = formatAddress(customer);
  const customerPhone = customer?.phone || "Not provided";
  const customerName = customer?.name || customer?.email || "Customer";
  const paymentMethod = formatPaymentMethodLabel(invoice?.paymentMethodType, invoice?.paymentReferenceCode);
  const pageMargin = 44;

  const pdfBuffer = await new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 0,
      info: {
        Title: `Invoice ${invoice.invoiceNumber}`,
        Author: "ElevenOrbits",
      },
    });
    const stream = new PassThrough();
    const chunks = [];

    stream.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    stream.on("finish", () => resolve(Buffer.concat(chunks)));
    stream.on("error", reject);
    doc.on("error", reject);
    doc.pipe(stream);

    const contentWidth = doc.page.width - pageMargin * 2;
    const footerReservedHeight = 76;
    const footerText = `Questions about this invoice? Contact ${supportEmail}.`;
    let cursorY = pageMargin;

    const getBottomLimit = () => doc.page.height - pageMargin - footerReservedHeight;

    const drawPageBackground = () => {
      doc.save();
      doc.rect(0, 0, doc.page.width, doc.page.height).fill(palette.page);
      doc.restore();
    };

    const drawFooter = () => {
      const footerY = doc.page.height - 54;

      doc.save();
      doc.strokeColor(palette.subtle).lineWidth(1);
      doc.moveTo(pageMargin, footerY - 12).lineTo(pageMargin + contentWidth, footerY - 12).stroke();
      doc.font("Helvetica").fontSize(10).fillColor(palette.muted).text(footerText, pageMargin, footerY, {
        width: contentWidth,
        align: "center",
      });
      doc.restore();
    };

    const addPage = () => {
      drawFooter();
      doc.addPage();
      drawPageBackground();
      cursorY = pageMargin;
    };

    const ensureSpace = (requiredHeight) => {
      if (cursorY + requiredHeight > getBottomLimit()) {
        addPage();
      }
    };

    const drawTableHeader = ({ continued = false } = {}) => {
      ensureSpace(58);
      doc.font("Helvetica-Bold").fontSize(14).fillColor(palette.text).text(
        continued ? "Invoice Items (continued)" : "Invoice Items",
        pageMargin,
        cursorY,
      );
      cursorY += 18;

      doc.fillColor(palette.tableHeader);
      doc.roundedRect(pageMargin, cursorY, contentWidth, 34, 12).fill();
      doc.font("Helvetica-Bold").fontSize(10).fillColor(palette.text).text("Service", tableColumns.item, cursorY + 11, {
        width: contentWidth - 260,
      });
      doc.text("Qty", tableColumns.qty, cursorY + 11, { width: 28, align: "right" });
      doc.text("Rate", tableColumns.rate, cursorY + 11, { width: 56, align: "right" });
      doc.text("Amount", tableColumns.amount, cursorY + 11, { width: 46, align: "right" });
      cursorY += 42;
    };

    drawPageBackground();

    doc.save();
    doc.fillColor(palette.header);
    doc.roundedRect(pageMargin, cursorY, contentWidth, 118, 24).fill();

    const logoExists = fs.existsSync(companyLogoPath);
    if (logoExists) {
      doc.image(companyLogoPath, pageMargin + 20, cursorY + 22, {
        fit: [66, 66],
        align: "left",
        valign: "center",
      });
    }

    const brandX = pageMargin + (logoExists ? 102 : 24);
    doc.font("Helvetica-Bold").fontSize(24).fillColor("#ffffff").text("ElevenOrbits", brandX, cursorY + 26, {
      width: 250,
    });
    doc.font("Helvetica").fontSize(11).fillColor("#cbd5e1").text("Powering Your Digital Universe", brandX, cursorY + 56, {
      width: 250,
    });
    doc.text(`Support: ${supportEmail}`, brandX, cursorY + 74, { width: 250 });

    doc.font("Helvetica-Bold").fontSize(13).fillColor("#bfdbfe").text("INVOICE", pageMargin, cursorY + 28, {
      width: contentWidth - 20,
      align: "right",
    });
    doc.font("Helvetica-Bold").fontSize(21).fillColor("#ffffff").text(invoice.invoiceNumber, pageMargin, cursorY + 46, {
      width: contentWidth - 20,
      align: "right",
    });
    drawStatusBadge(doc, invoice.status, pageMargin + contentWidth - 18, cursorY + 82);
    doc.restore();

    cursorY += 138;

    const cardGap = 18;
    const cardWidth = (contentWidth - cardGap) / 2;
    const billToX = pageMargin;
    const summaryX = billToX + cardWidth + cardGap;
    const detailWidth = cardWidth - 36;
    const detailRowGap = 10;
    const billToRows = [
      ["Name", customerName],
      ["Email", customer?.email || "Not provided"],
      ["Phone Number", customerPhone],
      ["Address", customerAddress],
    ];
    const summaryRows = [
      ["Service", planName || "Managed Service"],
      ["Billing Cycle", formatBillingCycle(invoice.billingCycle)],
      ["Issued On", formatDate(invoice.issuedAt)],
      ["Paid On", invoice.status === "paid" ? formatDate(invoice.paidAt) : "Pending"],
      ["Payment Method", paymentMethod],
      ["Payment Reference", invoice.paymentReferenceCode || "Pending"],
      ["Invoice Total", formatMoney(invoice.amount, invoice.currency)],
    ];
    const billToHeight = getKeyValueGroupHeight(doc, {
      width: detailWidth,
      rows: billToRows,
      gap: detailRowGap,
    });
    const summaryHeight = getKeyValueGroupHeight(doc, {
      width: detailWidth,
      rows: summaryRows,
      gap: detailRowGap,
    });
    const cardHeight = Math.max(220, 64 + Math.max(billToHeight, summaryHeight));

    ensureSpace(cardHeight + 24);
    drawOutlinedCard(doc, billToX, cursorY, cardWidth, cardHeight);
    drawOutlinedCard(doc, summaryX, cursorY, cardWidth, cardHeight);

    doc.font("Helvetica-Bold").fontSize(11).fillColor(palette.text).text("Bill To", billToX + 18, cursorY + 18);
    let billToCursorY = cursorY + 46;
    billToRows.forEach(([label, value], index) => {
      billToCursorY += drawKeyValue(doc, {
        x: billToX + 18,
        y: billToCursorY,
        width: detailWidth,
        label,
        value,
      });

      if (index < billToRows.length - 1) {
        billToCursorY += detailRowGap;
      }
    });

    doc.font("Helvetica-Bold").fontSize(11).fillColor(palette.text).text("Invoice Details", summaryX + 18, cursorY + 18);
    let summaryCursorY = cursorY + 46;
    summaryRows.forEach(([label, value], index) => {
      summaryCursorY += drawKeyValue(doc, {
        x: summaryX + 18,
        y: summaryCursorY,
        width: detailWidth,
        label,
        value,
      });

      if (index < summaryRows.length - 1) {
        summaryCursorY += detailRowGap;
      }
    });

    cursorY += cardHeight + 24;

    const tableColumns = {
      item: pageMargin + 18,
      qty: pageMargin + contentWidth - 190,
      rate: pageMargin + contentWidth - 132,
      amount: pageMargin + contentWidth - 62,
    };

    drawTableHeader();

    normalizedItems.forEach((item) => {
      const labelWidth = contentWidth - 260;
      const labelHeight = measureTextBlockHeight(doc, {
        text: item.label,
        width: labelWidth,
        font: "Helvetica",
        fontSize: 11,
      });
      const rowHeight = Math.max(34, labelHeight + 18);

      if (cursorY + rowHeight > getBottomLimit()) {
        addPage();
        drawTableHeader({ continued: true });
      }

      doc.strokeColor(palette.border).lineWidth(1);
      doc.moveTo(pageMargin, cursorY + rowHeight - 4).lineTo(pageMargin + contentWidth, cursorY + rowHeight - 4).stroke();
      doc.font("Helvetica").fontSize(11).fillColor(palette.text).text(item.label, tableColumns.item, cursorY + 6, {
        width: labelWidth,
      });
      doc.text(String(item.quantity), tableColumns.qty, cursorY + 6, {
        width: 28,
        align: "right",
      });
      doc.text(formatMoney(item.unitAmount, invoice.currency), tableColumns.rate - 6, cursorY + 6, {
        width: 62,
        align: "right",
      });
      doc.text(formatMoney(item.amount, invoice.currency), tableColumns.amount - 6, cursorY + 6, {
        width: 52,
        align: "right",
      });
      cursorY += rowHeight;
    });

    cursorY += 18;

    const noteWidth = contentWidth - 228;
    const paymentNote =
      invoice.status === "paid"
        ? `Payment has been verified through ${paymentMethod}.`
        : `Payment is currently marked as ${humanizeValue(invoice.status, "Pending")}. Reference ${
            invoice.paymentReferenceCode || "will appear after submission"
          }.`;
    const noteTextHeight = measureTextBlockHeight(doc, {
      text: paymentNote,
      width: noteWidth,
      font: "Helvetica",
      fontSize: 11,
    });
    const totalsHeight = 108;
    const paymentSectionHeight = Math.max(totalsHeight, 42 + noteTextHeight);

    ensureSpace(paymentSectionHeight);

    doc.font("Helvetica-Bold").fontSize(10).fillColor(palette.muted).text("PAYMENT NOTES", pageMargin, cursorY + 8, {
      width: noteWidth,
    });
    doc.font("Helvetica").fontSize(11).fillColor(palette.text).text(paymentNote, pageMargin, cursorY + 24, {
      width: noteWidth,
    });

    const totalsX = pageMargin + contentWidth - 210;
    drawOutlinedCard(doc, totalsX, cursorY, 210, totalsHeight);
    drawKeyValue(doc, {
      x: totalsX + 18,
      y: cursorY + 16,
      width: 174,
      label: "Subtotal",
      value: formatMoney(subtotal, invoice.currency),
    });
    drawKeyValue(doc, {
      x: totalsX + 18,
      y: cursorY + 50,
      width: 174,
      label: invoice.status === "paid" ? "Amount Paid" : "Amount Due",
      value: formatMoney(invoice.amount, invoice.currency),
    });

    cursorY += paymentSectionHeight + 24;

    const disclaimerWidth = contentWidth - 36;
    const disclaimerHeight = Math.max(
      112,
      52 +
        measureTextBlockHeight(doc, {
          text: invoiceDisclaimer,
          width: disclaimerWidth,
          font: "Helvetica",
          fontSize: 9,
        }),
    );

    ensureSpace(disclaimerHeight);
    drawOutlinedCard(doc, pageMargin, cursorY, contentWidth, disclaimerHeight);
    doc.font("Helvetica-Bold").fontSize(9).fillColor(palette.muted).text("DISCLAIMER", pageMargin + 18, cursorY + 16, {
      width: disclaimerWidth,
    });
    doc.font("Helvetica").fontSize(9).fillColor(palette.text).text(invoiceDisclaimer, pageMargin + 18, cursorY + 34, {
      width: disclaimerWidth,
      lineGap: 2,
    });

    drawFooter();

    doc.end();
  });

  writeBufferToFile(filePath, pdfBuffer);

  let uploadedFile = null;
  if (isObjectStorageEnabled()) {
    try {
      uploadedFile = await uploadBufferToStorage({
        key: storageKey,
        data: pdfBuffer,
        contentType: "application/pdf",
      });
    } catch (error) {
      console.error("Invoice PDF upload to object storage failed", error);
    }
  }

  return {
    pdfPath: filePath,
    pdfUrl: uploadedFile?.publicUrl || fileUrl,
    pdfStorageKey: uploadedFile?.storageKey || storageKey,
    pdfStorageProvider: uploadedFile?.storageProvider || "local",
  };
}
