const managedOps = [
  "Managed by ElevenOrbits Team",
  "24/7 operational oversight",
  "Ticketed support and change handling",
];

export const serviceCategories = [
  {
    name: "Managed VPS",
    slug: "vps",
    description: "Production-ready managed virtual private servers for business workloads.",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Managed VDS",
    slug: "vds",
    description: "Higher-isolation managed virtual dedicated servers with dedicated resources.",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Servers",
    slug: "ai-servers",
    description: "Managed GPU and AI compute nodes for inference, training, and private deployments.",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Vicidial Management",
    slug: "vicidial",
    description: "Managed call-center dialer operations, tuning, and lifecycle support.",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Workflow Automation",
    slug: "workflows",
    description: "Managed n8n automation, orchestration, and AI-assisted workflow delivery.",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "AI Solutions",
    slug: "ai-solutions",
    description: "Managed AI products, APIs, agents, and deployment guidance.",
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Development Support",
    slug: "development-support",
    description: "Technical support coverage, implementation help, and managed change support.",
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Managed hardening, monitoring, and security response coverage.",
    isActive: true,
    sortOrder: 8,
  },
  {
    name: "Managed CDN",
    slug: "cdn",
    description: "Managed content delivery, caching, image optimization, DDoS protection, and edge performance for high-traffic sites.",
    isActive: true,
    sortOrder: 9,
  },
  {
    name: "O7 Bucket",
    slug: "object-storage",
    description: "Fixed-price S3-compatible bucket storage with gated access, CORS configuration, and custom domain support.",
    isActive: true,
    sortOrder: 10,
  },
  {
    name: "Hermes AI Hosting",
    slug: "hermes-ai-hosting",
    description: "Managed self-hosted Hermes AI agent VPS plans with one-click install, memory, tools, and private agent operations.",
    isActive: true,
    sortOrder: 11,
  },
  {
    name: "OpenClaw Hosting",
    slug: "openclaw-hosting",
    description: "Managed self-hosted OpenClaw assistant VPS plans for always-on automation, messaging integrations, and private AI workflows.",
    isActive: true,
    sortOrder: 12,
  },
  {
    name: "Nextcloud Hosting",
    slug: "nextcloud-hosting",
    description: "Managed self-hosted Nextcloud plans for private file sync, sharing, backup, calendars, contacts, and collaboration.",
    isActive: true,
    sortOrder: 13,
  },
];

export const serviceFamilies = [
  {
    name: "Managed Cloud",
    description: "Managed VPS, VDS, CDN, O7 Bucket storage, and self-hosted app infrastructure under one operating model.",
    categorySlugs: ["vps", "vds", "cdn", "object-storage", "hermes-ai-hosting", "openclaw-hosting", "nextcloud-hosting"],
    includes: ["VPS", "VDS", "CDN", "O7 Bucket", "Hosted Apps"],
    techHighlights: ["KVM / Proxmox", "S3-compatible storage", "Managed CDN", "Self-hosted apps"],
  },
  {
    name: "Call Centers",
    description: "Dialer operations, support workflows, and service coordination for active teams.",
    categorySlugs: ["vicidial", "development-support"],
    includes: ["Vicidial", "Support"],
    techHighlights: ["Vicidial", "Asterisk", "SIP routing", "Operational runbooks"],
  },
  {
    name: "AI Services",
    description: "AI-ready infrastructure, automation layers, and managed model services.",
    categorySlugs: ["ai-servers", "workflows", "ai-solutions"],
    includes: ["AI Servers", "Workflow Automation", "AI Solutions"],
    techHighlights: ["GPU compute", "n8n", "DeepSeek", "Clawbot"],
  },
  {
    name: "Cybersecurity",
    description: "Managed security posture hardening and incident readiness for hosted systems.",
    categorySlugs: ["cybersecurity"],
    includes: ["Basic", "Premium", "Platinum"],
    techHighlights: ["WAF", "SIEM", "EDR", "Patch governance"],
  },
];

const selfHostedAppPlanSeeds = [
  {
    name: "Hermes AI Personal VPS",
    slug: "hermes-ai-personal-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for one person running a private daily AI assistant.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "4 vCPU cores", "8 GB RAM", "75 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "4 vCPU", "8 GB RAM", "75 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Hermes AI Power User VPS",
    slug: "hermes-ai-power-user-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for daily use across more tools, integrations, and agent sessions.",
    monthlyPrice: 12.96,
    yearlyPrice: 155.52,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "6 vCPU cores", "12 GB RAM", "100 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "6 vCPU", "12 GB RAM", "100 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$12.96/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Hermes AI Team Deployment VPS",
    slug: "hermes-ai-team-deployment-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for small teams with multiple subagents running in parallel.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "12 vCPU cores", "48 GB RAM", "250 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "12 vCPU", "48 GB RAM", "250 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Hermes AI Enterprise Scale VPS",
    slug: "hermes-ai-enterprise-scale-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for complex pipelines, heavier parallel workloads, and enterprise agent operations.",
    monthlyPrice: 84.67,
    yearlyPrice: 1016.04,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "18 vCPU cores", "96 GB RAM", "350 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "18 vCPU", "96 GB RAM", "350 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$84.67/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "OpenClaw Personal VPS",
    slug: "openclaw-personal-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for individuals running a private always-on AI assistant.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "4 vCPU cores", "8 GB RAM", "75 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "4 vCPU", "8 GB RAM", "75 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "OpenClaw Power User VPS",
    slug: "openclaw-power-user-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for heavier use across messaging platforms, tools, and workflow integrations.",
    monthlyPrice: 12.96,
    yearlyPrice: 155.52,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "6 vCPU cores", "12 GB RAM", "100 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "6 vCPU", "12 GB RAM", "100 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$12.96/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "OpenClaw Team Deployment VPS",
    slug: "openclaw-team-deployment-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for small teams with advanced automation and multiple workflows.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "12 vCPU cores", "48 GB RAM", "250 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "12 vCPU", "48 GB RAM", "250 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "OpenClaw Enterprise Scale VPS",
    slug: "openclaw-enterprise-scale-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for complex AI workflows, heavy integrations, and larger automation workloads.",
    monthlyPrice: 84.67,
    yearlyPrice: 1016.04,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "16 vCPU cores", "64 GB RAM", "500 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "16 vCPU", "64 GB RAM", "500 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$84.67/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Nextcloud Starter",
    slug: "nextcloud-starter",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for individuals, families, or small teams syncing files, calendars, and contacts.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "4 vCPU cores", "8 GB RAM", "150 GB SSD / 75 GB NVMe", "Full data control"],
    techStack: ["Nextcloud", "4 vCPU", "8 GB RAM", "150 GB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Nextcloud Large Media Libraries",
    slug: "nextcloud-large-media-libraries",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting with 1 TB storage for creators, media libraries, backups, and large file sharing.",
    monthlyPrice: 24.19,
    yearlyPrice: 290.28,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "6 vCPU cores", "18 GB RAM", "1 TB SSD", "Full data control"],
    techStack: ["Nextcloud", "6 vCPU", "18 GB RAM", "1 TB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$24.19/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Nextcloud Business Needs",
    slug: "nextcloud-business-needs",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for growing businesses with active users, apps, sharing, and collaboration.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "12 vCPU cores", "48 GB RAM", "500 GB SSD / 250 GB NVMe", "Full data control"],
    techStack: ["Nextcloud", "12 vCPU", "48 GB RAM", "500 GB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Nextcloud Ultimate Media Server",
    slug: "nextcloud-ultimate-media-server",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for extensive media collections, streaming, backups, and large collaboration spaces.",
    monthlyPrice: 64.08,
    yearlyPrice: 768.96,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "14 vCPU cores", "50 GB RAM", "1.4 TB SSD", "1 Gbit/s port"],
    techStack: ["Nextcloud", "14 vCPU", "50 GB RAM", "1.4 TB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$64.08/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 4,
  },
];

export const productPlanSeeds = [
  {
    name: "Basic Managed VPS",
    slug: "basic-managed-vps",
    categorySlug: "vps",
    description: "Entry managed VPS for websites, apps, and low-risk production services.",
    monthlyPrice: 100,
    yearlyPrice: 960,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "OS hardening and patching", "1 managed environment"],
    techStack: ["Ubuntu / AlmaLinux", "Nginx / Apache", "Managed firewall"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Pro Managed VPS",
    slug: "pro-managed-vps",
    categorySlug: "vps",
    description: "Managed VPS with more headroom for scaling applications and operations.",
    monthlyPrice: 150,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Advanced support routing", "Performance review"],
    techStack: ["Ubuntu / AlmaLinux", "Docker", "Nginx", "Daily backup rotation"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$150/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Elite Managed VPS",
    slug: "elite-managed-vps",
    categorySlug: "vps",
    description: "Premium VPS operations with tighter escalation and managed service coverage.",
    monthlyPrice: 200,
    yearlyPrice: 1920,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Dedicated escalation channel", "Priority maintenance window"],
    techStack: ["Ubuntu / AlmaLinux", "Container orchestration", "WAF rules", "Priority monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$200/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Windows 4GB VPS",
    slug: "windows-4gb-vps",
    categorySlug: "vps",
    description: "Managed Windows Server VPS with Remote Desktop access for small business workloads.",
    monthlyPrice: 20,
    yearlyPrice: 240,
    yearlyDiscountPercent: 0,
    features: [
      ...managedOps,
      "2 vCPU cores",
      "4 GB RAM",
      "2 TB bandwidth",
      "40 GB disk space",
      "Dedicated IP",
      "Remote Desktop access",
      "Windows Server",
      "Setup time 24 to 48 hours",
      "US and UK locations",
      "Non-refundable VPS",
    ],
    techStack: ["Windows Server", "2 vCPU", "4 GB RAM", "40 GB Disk", "2 TB Bandwidth"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$20/mo",
    serviceType: "managed_windows_vps",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Windows 8GB VPS",
    slug: "windows-8gb-vps",
    categorySlug: "vps",
    description: "Managed Windows Server VPS with more memory and bandwidth for active applications.",
    monthlyPrice: 40,
    yearlyPrice: 480,
    yearlyDiscountPercent: 0,
    features: [
      ...managedOps,
      "4 vCPU cores",
      "8 GB RAM",
      "5 TB bandwidth",
      "60 GB disk space",
      "Dedicated IP",
      "Remote Desktop access",
      "Windows Server",
      "Setup time 24 to 48 hours",
      "US and UK locations",
      "Non-refundable VPS",
    ],
    techStack: ["Windows Server", "4 vCPU", "8 GB RAM", "60 GB Disk", "5 TB Bandwidth"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$40/mo",
    serviceType: "managed_windows_vps",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "Windows 16GB VPS",
    slug: "windows-16gb-vps",
    categorySlug: "vps",
    description: "Managed Windows Server VPS for larger remote desktop and application workloads.",
    monthlyPrice: 60,
    yearlyPrice: 720,
    yearlyDiscountPercent: 0,
    features: [
      ...managedOps,
      "6 vCPU cores",
      "16 GB RAM",
      "5 TB bandwidth",
      "120 GB disk space",
      "Dedicated IP",
      "Remote Desktop access",
      "Windows Server",
      "Setup time 24 to 48 hours",
      "US and UK locations",
      "Non-refundable VPS",
    ],
    techStack: ["Windows Server", "6 vCPU", "16 GB RAM", "120 GB Disk", "5 TB Bandwidth"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$60/mo",
    serviceType: "managed_windows_vps",
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Windows 32GB VPS",
    slug: "windows-32gb-vps",
    categorySlug: "vps",
    description: "Managed Windows Server VPS for heavier remote desktop, automation, and business workloads.",
    monthlyPrice: 90,
    yearlyPrice: 1080,
    yearlyDiscountPercent: 0,
    features: [
      ...managedOps,
      "8 vCPU cores",
      "32 GB RAM",
      "10 TB bandwidth",
      "240 GB disk space",
      "Dedicated IP",
      "Remote Desktop access",
      "Windows Server",
      "Setup time 24 to 48 hours",
      "US and UK locations",
      "Non-refundable VPS",
    ],
    techStack: ["Windows Server", "8 vCPU", "32 GB RAM", "240 GB Disk", "10 TB Bandwidth"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$90/mo",
    serviceType: "managed_windows_vps",
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Balanced Managed VDS",
    slug: "balanced-managed-vds",
    categorySlug: "vds",
    description: "Dedicated-resource VDS for stable workloads needing stronger isolation.",
    monthlyPrice: 140,
    yearlyPrice: 1512,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Dedicated vCPU allocation", "Managed baseline tuning"],
    techStack: ["KVM / Proxmox", "Ubuntu / Debian", "Managed snapshots"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$140/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Business Managed VDS",
    slug: "business-managed-vds",
    categorySlug: "vds",
    description: "Business VDS with stronger performance and managed scaling guidance.",
    monthlyPrice: 220,
    yearlyPrice: 2376,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Managed scaling review", "Capacity planning assistance"],
    techStack: ["KVM / Proxmox", "AlmaLinux / Ubuntu", "Managed firewall and backups"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$220/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Enterprise Managed VDS",
    slug: "enterprise-managed-vds",
    categorySlug: "vds",
    description: "High-capacity managed VDS for heavier business systems and bespoke requirements.",
    monthlyPrice: 320,
    yearlyPrice: 3456,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority change coordination", "Dedicated technical planning"],
    techStack: ["KVM / Proxmox", "Load-balanced services", "Managed backup retention"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$320/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "AI Server Starter",
    slug: "ai-server-starter",
    categorySlug: "ai-servers",
    description: "Managed GPU-ready server delivery for small inference and model-serving workloads.",
    monthlyPrice: 260,
    yearlyPrice: 2808,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "GPU environment setup", "Inference deployment support"],
    techStack: ["CUDA-ready GPU node", "PyTorch / vLLM", "Docker", "Model monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$260/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "AI Server Scale",
    slug: "ai-server-scale",
    categorySlug: "ai-servers",
    description: "Managed AI infrastructure for growing internal or customer-facing AI services.",
    monthlyPrice: 420,
    yearlyPrice: 4536,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Model rollout support", "Operational performance reviews"],
    techStack: ["GPU cluster node", "Kubernetes / Docker", "Observability stack", "Private model serving"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$420/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Server Enterprise",
    slug: "ai-server-enterprise",
    categorySlug: "ai-servers",
    description: "Enterprise AI compute deployment with custom architecture and operational planning.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Dedicated rollout plan", "Private infrastructure design", "Custom security controls"],
    techStack: ["GPU clusters", "Private networking", "Registry and artifact controls", "Custom observability"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Starter Vicidial Management",
    slug: "starter-vicidial-management",
    categorySlug: "vicidial",
    description: "Managed Vicidial support for smaller calling teams.",
    monthlyPrice: 50,
    yearlyPrice: 600,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Routine maintenance", "Queue review support"],
    techStack: ["Vicidial", "Asterisk", "SIP trunk setup"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$50/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Growth Vicidial Management",
    slug: "growth-vicidial-management",
    categorySlug: "vicidial",
    description: "Broader dialer management for growing call-center operations.",
    monthlyPrice: 80,
    yearlyPrice: 960,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Performance tuning", "Priority support queue"],
    techStack: ["Vicidial", "Asterisk", "Call recording review", "SIP routing"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$80/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Premium Vicidial Management",
    slug: "premium-vicidial-management",
    categorySlug: "vicidial",
    description: "High-touch management for larger Vicidial and call-center operations.",
    monthlyPrice: 100,
    yearlyPrice: 1200,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Advanced routing review", "Priority escalation"],
    techStack: ["Vicidial", "Asterisk", "SIP routing", "QA workflow support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Workflow Starter",
    slug: "workflow-starter",
    categorySlug: "workflows",
    description: "Managed n8n workflow automation with a focused app footprint.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: ["3 integrated apps", ...managedOps, "AI workflow guidance"],
    techStack: ["n8n", "Webhook orchestration", "DeepSeek / OpenAI integration"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Workflow Growth",
    slug: "workflow-growth",
    categorySlug: "workflows",
    description: "Expanded workflow automation with more integrations and revision capacity.",
    monthlyPrice: 75,
    yearlyPrice: 900,
    yearlyDiscountPercent: 0,
    features: ["5 integrated apps", ...managedOps, "Monitoring and revisions"],
    techStack: ["n8n", "Webhook routing", "Vector / AI integrations", "Monitoring"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$75/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Workflow Enterprise",
    slug: "workflow-enterprise",
    categorySlug: "workflows",
    description: "Enterprise automation architecture with custom integrations and operational support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom app integrations", "Solution architecture", "Dedicated support"],
    techStack: ["n8n", "Custom APIs", "Queue / event design", "Governed deployment"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "automation",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Clawbot",
    slug: "clawbot",
    categorySlug: "ai-solutions",
    description: "Deploy and manage Clawbot-based AI workflows and customer-facing automation.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Managed rollout", "Prompt operations support", "Business automation advisory"],
    techStack: ["Clawbot", "Prompt operations", "Workflow integrations"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "DeepSeek API Access",
    slug: "deepseek-api-access",
    categorySlug: "ai-solutions",
    description: "Managed DeepSeek API access, guardrails, and implementation support.",
    monthlyPrice: 120,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Usage guidance", "Integration support"],
    techStack: ["DeepSeek API", "Usage policy controls", "Integration support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$120/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Open-Source DeepSeek Services",
    slug: "open-source-deepseek-services",
    categorySlug: "ai-solutions",
    description: "Managed open-source DeepSeek deployment and private model service support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Model hosting guidance", "Ops and scaling support", "Custom deployment"],
    techStack: ["Open-source DeepSeek", "vLLM / Ollama", "Private deployment controls"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Managed Support Basic",
    slug: "managed-support-basic",
    categorySlug: "development-support",
    description: "Recurring support coverage for operations teams needing hands-on technical help.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Monthly support allocation", "Ticket support"],
    techStack: ["Ticket queue support", "Runbook execution", "Infrastructure troubleshooting"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "support",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Advanced Development Support",
    slug: "advanced-development-support",
    categorySlug: "development-support",
    description: "Managed implementation and technical support for more complex change requests.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom engineering support", "Architecture review", "Priority coordination"],
    techStack: ["Application support", "Release coordination", "Architecture guidance"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "support",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Basic",
    slug: "cybersecurity-basic",
    categorySlug: "cybersecurity",
    description: "Foundational security hardening and routine monitoring for hosted systems.",
    monthlyPrice: 90,
    yearlyPrice: 972,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Baseline hardening checklist", "Security alert triage"],
    techStack: ["Firewall policy review", "OS hardening", "Fail2Ban / WAF"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$90/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Cybersecurity Premium",
    slug: "cybersecurity-premium",
    categorySlug: "cybersecurity",
    description: "Broader monitoring, response coordination, and managed hardening coverage.",
    monthlyPrice: 170,
    yearlyPrice: 1836,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "WAF tuning", "Incident response coordination", "Monthly posture review"],
    techStack: ["WAF / reverse proxy", "SIEM ingestion", "Patch governance"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$170/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Platinum",
    slug: "cybersecurity-platinum",
    categorySlug: "cybersecurity",
    description: "Premium managed security operations with faster response and deeper review cadence.",
    monthlyPrice: 280,
    yearlyPrice: 3024,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority incident handling", "Security change planning", "Executive risk summary"],
    techStack: ["WAF", "SIEM", "EDR guidance", "Response playbooks"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$280/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Standard Managed CDN",
    slug: "standard-managed-cdn",
    categorySlug: "cdn",
    description: "Managed CDN for essential edge performance, image optimization, custom caching, and DDoS protection.",
    monthlyPrice: 72,
    yearlyPrice: 864,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Full image optimization", "Custom caching rules", "Built-in DDoS protection", "Up to 2 TB monthly traffic", "14-day trial included"],
    techStack: ["Managed CDN", "Edge caching", "Image optimization", "DDoS protection"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$72/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Premium Managed CDN",
    slug: "premium-managed-cdn",
    categorySlug: "cdn",
    description: "Managed CDN for content-heavy businesses that need priority caching, analytics, and stronger security controls.",
    monthlyPrice: 315,
    yearlyPrice: 3780,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Priority caching", "Real-time analytics", "Full security suite", "10 TB monthly traffic", "14-day trial included"],
    techStack: ["Managed CDN", "Priority caching", "Real-time analytics", "Security rules"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$315/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Unlimited Managed CDN",
    slug: "unlimited-managed-cdn",
    categorySlug: "cdn",
    description: "Enterprise CDN coverage with unlimited traffic, dedicated support, and the full optimization and security suite.",
    monthlyPrice: 1798.2,
    yearlyPrice: 21578.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Full optimization suite", "Full DDoS and security suite", "Dedicated support", "Unlimited traffic", "14-day trial included"],
    techStack: ["Managed CDN", "Dedicated support", "Security suite", "Traffic optimization"],
    planType: "enterprise",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$1,798.20/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "O7 Bucket 250 GB",
    slug: "object-storage-250gb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for small backup sets, application assets, development environments, and gated file access.",
    monthlyPrice: 31.25,
    yearlyPrice: 375,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "250 GB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$31.25/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "O7 Bucket 500 GB",
    slug: "object-storage-500gb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for growing media libraries, backups, staging assets, and S3-compatible app workflows.",
    monthlyPrice: 62.5,
    yearlyPrice: 750,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "500 GB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$62.50/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "O7 Bucket 1 TB",
    slug: "object-storage-1tb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for production backups, content libraries, application data, and developer S3 API access.",
    monthlyPrice: 125,
    yearlyPrice: 1500,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "1 TB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$125/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "O7 Bucket 2 TB",
    slug: "object-storage-2tb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for larger backup, archive, media delivery, and controlled application object workflows.",
    monthlyPrice: 250,
    yearlyPrice: 3000,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "2 TB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$250/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "O7 Bucket 5 TB",
    slug: "object-storage-5tb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for high-volume files, backups, media repositories, AI datasets, and gated delivery.",
    monthlyPrice: 625,
    yearlyPrice: 7500,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "5 TB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$625/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "O7 Bucket 10 TB",
    slug: "object-storage-10tb",
    categorySlug: "object-storage",
    description: "Fixed monthly O7 Bucket storage for large archives, AI datasets, media repositories, backup estates, and custom-domain object delivery.",
    monthlyPrice: 1250,
    yearlyPrice: 15000,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "10 TB included capacity", "$0.125 per GB fixed monthly pricing", "S3-compatible API access", "Gated access with CORS policy", "Custom domain support"],
    techStack: ["O7 Bucket", "S3-compatible API", "CORS policy", "Custom domain"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$1,250/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 6,
  },
  ...selfHostedAppPlanSeeds,
];

const serverCommerceCategorySlugs = ["vps", "vds"];

const serverRegionAddonTemplates = [
  {
    name: "European Union",
    optionCode: "region-eu",
    description: "Low-latency European deployment region.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 10,
  },
  {
    name: "United States (West)",
    optionCode: "region-us-west",
    description: "West coast region for American traffic routing.",
    monthlyPrice: 2.2,
    yearlyPrice: 26.4,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 20,
  },
  {
    name: "Asia (Singapore)",
    optionCode: "region-asia-singapore",
    description: "APAC-friendly region with strong Southeast Asia coverage.",
    monthlyPrice: 4.4,
    yearlyPrice: 52.8,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 30,
  },
];

const serverStorageAddonTemplates = [
  {
    name: "SSD",
    optionCode: "storage-ssd",
    description: "General-purpose SSD storage with a generous included base allocation.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 200,
    pricePerUnitMonthly: 0.012,
    pricePerUnitYearly: 0.144,
    unitLabel: "GB",
    minQuantity: 200,
    quantityStep: 50,
    sortOrder: 40,
  },
  {
    name: "NVMe",
    optionCode: "storage-nvme",
    description: "Higher-throughput NVMe storage for workloads that need faster I/O.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 100,
    pricePerUnitMonthly: 0.0315,
    pricePerUnitYearly: 0.378,
    unitLabel: "GB",
    minQuantity: 100,
    quantityStep: 50,
    sortOrder: 50,
  },
];

const serverImageAddonTemplates = [
  {
    name: "Ubuntu",
    optionCode: "image-ubuntu",
    description: "Ubuntu LTS server image.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 60,
  },
  {
    name: "Custom Images",
    optionCode: "image-custom",
    description: "Bring a prepared custom image for deployment.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 70,
  },
  {
    name: "Windows Server",
    optionCode: "image-windows-server",
    description: "Licensed Windows Server image.",
    monthlyPrice: 19.1,
    yearlyPrice: 229.2,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 80,
  },
  {
    name: "cPanel",
    optionCode: "image-cpanel",
    description: "cPanel image with the required management licensing.",
    monthlyPrice: 27.5,
    yearlyPrice: 330,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 90,
  },
  {
    name: "RHEL Variants",
    optionCode: "image-rhel",
    description: "RHEL-compatible variants for enterprise-focused deployments.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 100,
  },
  {
    name: "Plesk + Linux",
    optionCode: "image-plesk-linux",
    description: "Plesk on Linux with the required control-panel licensing.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 110,
  },
];

export const addonSeeds = [
  {
    name: "Priority Escalation",
    categorySlug: "vps",
    description: "Faster response targets and dedicated operational escalation.",
    monthlyPrice: 20,
    yearlyPrice: 240,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-priority-escalation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vps",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vds",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Extra Workflow Revision Pack",
    categorySlug: "workflows",
    description: "Additional workflow refinement and optimization hours.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-workflow-revisions",
    isActive: true,
    sortOrder: 1,
  },
  ...serverCommerceCategorySlugs.flatMap((categorySlug) =>
    [...serverRegionAddonTemplates, ...serverStorageAddonTemplates, ...serverImageAddonTemplates].map((addon) => ({
      ...addon,
      categorySlug,
      isActive: true,
    })),
  ),
];

export const serviceMarketingContent = {
  vps: {
    headline: "Managed VPS for businesses that want hosting without operational overhead.",
    body: "Every VPS plan is operated by the ElevenOrbits team with monitoring, maintenance, and support built in.",
  },
  vds: {
    headline: "Managed VDS with dedicated resources and operational ownership.",
    body: "Use VDS when you need stronger resource isolation while keeping infrastructure management off your team.",
  },
  "ai-servers": {
    headline: "AI-ready infrastructure with managed deployment and support.",
    body: "Run inference or private-model workloads on managed compute while ElevenOrbits operates the platform.",
  },
  vicidial: {
    headline: "Vicidial management subscriptions for reliable call-center operations.",
    body: "We handle updates, tuning, SIP coordination, and support workflows so your agents stay focused.",
  },
  workflows: {
    headline: "Workflow automation on n8n with integrated AI services.",
    body: "Build dependable automations with managed integration, orchestration, and AI-assisted delivery.",
  },
  "ai-solutions": {
    headline: "AI products and managed APIs delivered with operational support.",
    body: "Use ElevenOrbits for managed AI product rollout, prompt operations, and private-model support.",
  },
  "development-support": {
    headline: "Managed support coverage for teams that need technical execution help.",
    body: "Use recurring support plans for implementation help, issue handling, and change coordination.",
  },
  cybersecurity: {
    headline: "Managed cybersecurity services for hosting, applications, and operational risk.",
    body: "Protect hosted systems with managed hardening, monitoring, incident coordination, and security reviews.",
  },
  cdn: {
    headline: "Managed CDN for fast, resilient content delivery across Europe.",
    body: "Accelerate websites with managed caching, image optimization, DDoS protection, unlimited domains, and operational support.",
  },
  "object-storage": {
    headline: "O7 Bucket storage with fixed monthly capacity pricing.",
    body: "Use O7 Bucket for S3-compatible developer access, gated delivery, CORS policies, custom domains, backups, media, archives, and AI datasets without customer-facing operation or ingress/egress overage metering.",
  },
  "hermes-ai-hosting": {
    headline: "Managed Hermes AI VPS hosting for private always-on agents.",
    body: "Run a self-hosted Hermes Agent with memory across sessions, private data control, tool integrations, app handoff, and managed VPS operations.",
  },
  "openclaw-hosting": {
    headline: "Managed OpenClaw VPS hosting for AI assistants that act for you.",
    body: "Host OpenClaw on a managed VPS for messaging integrations, automation, tool use, private data control, and customer portal access handoff.",
  },
  "nextcloud-hosting": {
    headline: "Managed Nextcloud hosting for private sync, sharing, backup, and collaboration.",
    body: "Launch a self-hosted Nextcloud private cloud with managed VPS resources, app handoff, unlimited users, data control, and support.",
  },
};
