const managedOps = [
  "Managed by ElevenOrbits Team",
  "24/7 operational oversight",
  "Ticketed support and change handling",
];

export const serviceCategories = [
  {
    name: "Managed VPS",
    slug: "vps",
    description: "Production-ready managed virtual private servers for business workloads.",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Managed VDS",
    slug: "vds",
    description: "Higher-isolation managed virtual dedicated servers with dedicated resources.",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Servers",
    slug: "ai-servers",
    description: "Managed GPU and AI compute nodes for inference, training, and private deployments.",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Vicidial Management",
    slug: "vicidial",
    description: "Managed call-center dialer operations, tuning, and lifecycle support.",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Workflow Automation",
    slug: "workflows",
    description: "Managed n8n automation, orchestration, and AI-assisted workflow delivery.",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "AI Solutions",
    slug: "ai-solutions",
    description: "Managed AI products, APIs, agents, and deployment guidance.",
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Development Support",
    slug: "development-support",
    description: "Technical support coverage, implementation help, and managed change support.",
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Managed hardening, monitoring, and security response coverage.",
    isActive: true,
    sortOrder: 8,
  },
];

export const serviceFamilies = [
  {
    name: "Servers",
    description: "Managed compute foundations for hosted applications and business systems.",
    categorySlugs: ["vps", "vds"],
    includes: ["VPS", "VDS"],
    techHighlights: ["KVM / Proxmox", "Ubuntu / AlmaLinux", "Nginx / Apache", "Managed backups"],
  },
  {
    name: "Call Centers",
    description: "Dialer operations, support workflows, and service coordination for active teams.",
    categorySlugs: ["vicidial", "development-support"],
    includes: ["Vicidial", "Support"],
    techHighlights: ["Vicidial", "Asterisk", "SIP routing", "Operational runbooks"],
  },
  {
    name: "AI Services",
    description: "AI-ready infrastructure, automation layers, and managed model services.",
    categorySlugs: ["ai-servers", "workflows", "ai-solutions"],
    includes: ["AI Servers", "Workflow Automation", "AI Solutions"],
    techHighlights: ["GPU compute", "n8n", "DeepSeek", "Clawbot"],
  },
  {
    name: "Cybersecurity",
    description: "Managed security posture hardening and incident readiness for hosted systems.",
    categorySlugs: ["cybersecurity"],
    includes: ["Basic", "Premium", "Platinum"],
    techHighlights: ["WAF", "SIEM", "EDR", "Patch governance"],
  },
];

export const productPlanSeeds = [
  {
    name: "Basic Managed VPS",
    slug: "basic-managed-vps",
    categorySlug: "vps",
    description: "Entry managed VPS for websites, apps, and low-risk production services.",
    monthlyPrice: 100,
    yearlyPrice: 960,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "OS hardening and patching", "1 managed environment"],
    techStack: ["Ubuntu / AlmaLinux", "Nginx / Apache", "Managed firewall"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Pro Managed VPS",
    slug: "pro-managed-vps",
    categorySlug: "vps",
    description: "Managed VPS with more headroom for scaling applications and operations.",
    monthlyPrice: 150,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Advanced support routing", "Performance review"],
    techStack: ["Ubuntu / AlmaLinux", "Docker", "Nginx", "Daily backup rotation"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$150/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Elite Managed VPS",
    slug: "elite-managed-vps",
    categorySlug: "vps",
    description: "Premium VPS operations with tighter escalation and managed service coverage.",
    monthlyPrice: 200,
    yearlyPrice: 1920,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Dedicated escalation channel", "Priority maintenance window"],
    techStack: ["Ubuntu / AlmaLinux", "Container orchestration", "WAF rules", "Priority monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$200/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Balanced Managed VDS",
    slug: "balanced-managed-vds",
    categorySlug: "vds",
    description: "Dedicated-resource VDS for stable workloads needing stronger isolation.",
    monthlyPrice: 140,
    yearlyPrice: 1512,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Dedicated vCPU allocation", "Managed baseline tuning"],
    techStack: ["KVM / Proxmox", "Ubuntu / Debian", "Managed snapshots"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$140/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Business Managed VDS",
    slug: "business-managed-vds",
    categorySlug: "vds",
    description: "Business VDS with stronger performance and managed scaling guidance.",
    monthlyPrice: 220,
    yearlyPrice: 2376,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Managed scaling review", "Capacity planning assistance"],
    techStack: ["KVM / Proxmox", "AlmaLinux / Ubuntu", "Managed firewall and backups"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$220/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Enterprise Managed VDS",
    slug: "enterprise-managed-vds",
    categorySlug: "vds",
    description: "High-capacity managed VDS for heavier business systems and bespoke requirements.",
    monthlyPrice: 320,
    yearlyPrice: 3456,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority change coordination", "Dedicated technical planning"],
    techStack: ["KVM / Proxmox", "Load-balanced services", "Managed backup retention"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$320/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "AI Server Starter",
    slug: "ai-server-starter",
    categorySlug: "ai-servers",
    description: "Managed GPU-ready server delivery for small inference and model-serving workloads.",
    monthlyPrice: 260,
    yearlyPrice: 2808,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "GPU environment setup", "Inference deployment support"],
    techStack: ["CUDA-ready GPU node", "PyTorch / vLLM", "Docker", "Model monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$260/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "AI Server Scale",
    slug: "ai-server-scale",
    categorySlug: "ai-servers",
    description: "Managed AI infrastructure for growing internal or customer-facing AI services.",
    monthlyPrice: 420,
    yearlyPrice: 4536,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Model rollout support", "Operational performance reviews"],
    techStack: ["GPU cluster node", "Kubernetes / Docker", "Observability stack", "Private model serving"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$420/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Server Enterprise",
    slug: "ai-server-enterprise",
    categorySlug: "ai-servers",
    description: "Enterprise AI compute deployment with custom architecture and operational planning.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Dedicated rollout plan", "Private infrastructure design", "Custom security controls"],
    techStack: ["GPU clusters", "Private networking", "Registry and artifact controls", "Custom observability"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Starter Vicidial Management",
    slug: "starter-vicidial-management",
    categorySlug: "vicidial",
    description: "Managed Vicidial support for smaller calling teams.",
    monthlyPrice: 50,
    yearlyPrice: 600,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Routine maintenance", "Queue review support"],
    techStack: ["Vicidial", "Asterisk", "SIP trunk setup"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$50/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Growth Vicidial Management",
    slug: "growth-vicidial-management",
    categorySlug: "vicidial",
    description: "Broader dialer management for growing call-center operations.",
    monthlyPrice: 80,
    yearlyPrice: 960,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Performance tuning", "Priority support queue"],
    techStack: ["Vicidial", "Asterisk", "Call recording review", "SIP routing"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$80/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Premium Vicidial Management",
    slug: "premium-vicidial-management",
    categorySlug: "vicidial",
    description: "High-touch management for larger Vicidial and call-center operations.",
    monthlyPrice: 100,
    yearlyPrice: 1200,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Advanced routing review", "Priority escalation"],
    techStack: ["Vicidial", "Asterisk", "SIP routing", "QA workflow support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Workflow Starter",
    slug: "workflow-starter",
    categorySlug: "workflows",
    description: "Managed n8n workflow automation with a focused app footprint.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: ["3 integrated apps", ...managedOps, "AI workflow guidance"],
    techStack: ["n8n", "Webhook orchestration", "DeepSeek / OpenAI integration"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Workflow Growth",
    slug: "workflow-growth",
    categorySlug: "workflows",
    description: "Expanded workflow automation with more integrations and revision capacity.",
    monthlyPrice: 75,
    yearlyPrice: 900,
    yearlyDiscountPercent: 0,
    features: ["5 integrated apps", ...managedOps, "Monitoring and revisions"],
    techStack: ["n8n", "Webhook routing", "Vector / AI integrations", "Monitoring"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$75/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Workflow Enterprise",
    slug: "workflow-enterprise",
    categorySlug: "workflows",
    description: "Enterprise automation architecture with custom integrations and operational support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom app integrations", "Solution architecture", "Dedicated support"],
    techStack: ["n8n", "Custom APIs", "Queue / event design", "Governed deployment"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "automation",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Clawbot",
    slug: "clawbot",
    categorySlug: "ai-solutions",
    description: "Deploy and manage Clawbot-based AI workflows and customer-facing automation.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Managed rollout", "Prompt operations support", "Business automation advisory"],
    techStack: ["Clawbot", "Prompt operations", "Workflow integrations"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "DeepSeek API Access",
    slug: "deepseek-api-access",
    categorySlug: "ai-solutions",
    description: "Managed DeepSeek API access, guardrails, and implementation support.",
    monthlyPrice: 120,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Usage guidance", "Integration support"],
    techStack: ["DeepSeek API", "Usage policy controls", "Integration support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$120/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Open-Source DeepSeek Services",
    slug: "open-source-deepseek-services",
    categorySlug: "ai-solutions",
    description: "Managed open-source DeepSeek deployment and private model service support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Model hosting guidance", "Ops and scaling support", "Custom deployment"],
    techStack: ["Open-source DeepSeek", "vLLM / Ollama", "Private deployment controls"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Managed Support Basic",
    slug: "managed-support-basic",
    categorySlug: "development-support",
    description: "Recurring support coverage for operations teams needing hands-on technical help.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Monthly support allocation", "Ticket support"],
    techStack: ["Ticket queue support", "Runbook execution", "Infrastructure troubleshooting"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "support",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Advanced Development Support",
    slug: "advanced-development-support",
    categorySlug: "development-support",
    description: "Managed implementation and technical support for more complex change requests.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom engineering support", "Architecture review", "Priority coordination"],
    techStack: ["Application support", "Release coordination", "Architecture guidance"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "support",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Basic",
    slug: "cybersecurity-basic",
    categorySlug: "cybersecurity",
    description: "Foundational security hardening and routine monitoring for hosted systems.",
    monthlyPrice: 90,
    yearlyPrice: 972,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Baseline hardening checklist", "Security alert triage"],
    techStack: ["Firewall policy review", "OS hardening", "Fail2Ban / WAF"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$90/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Cybersecurity Premium",
    slug: "cybersecurity-premium",
    categorySlug: "cybersecurity",
    description: "Broader monitoring, response coordination, and managed hardening coverage.",
    monthlyPrice: 170,
    yearlyPrice: 1836,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "WAF tuning", "Incident response coordination", "Monthly posture review"],
    techStack: ["WAF / reverse proxy", "SIEM ingestion", "Patch governance"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$170/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Platinum",
    slug: "cybersecurity-platinum",
    categorySlug: "cybersecurity",
    description: "Premium managed security operations with faster response and deeper review cadence.",
    monthlyPrice: 280,
    yearlyPrice: 3024,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority incident handling", "Security change planning", "Executive risk summary"],
    techStack: ["WAF", "SIEM", "EDR guidance", "Response playbooks"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$280/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 3,
  },
];

const serverCommerceCategorySlugs = ["vps", "vds"];

const serverRegionAddonTemplates = [
  {
    name: "European Union",
    optionCode: "region-eu",
    description: "Low-latency European deployment region.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 10,
  },
  {
    name: "United States (West)",
    optionCode: "region-us-west",
    description: "West coast region for American traffic routing.",
    monthlyPrice: 2.2,
    yearlyPrice: 26.4,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 20,
  },
  {
    name: "Asia (Singapore)",
    optionCode: "region-asia-singapore",
    description: "APAC-friendly region with strong Southeast Asia coverage.",
    monthlyPrice: 4.4,
    yearlyPrice: 52.8,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 30,
  },
];

const serverStorageAddonTemplates = [
  {
    name: "SSD",
    optionCode: "storage-ssd",
    description: "General-purpose SSD storage with a generous included base allocation.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 200,
    pricePerUnitMonthly: 0.012,
    pricePerUnitYearly: 0.144,
    unitLabel: "GB",
    minQuantity: 200,
    quantityStep: 50,
    sortOrder: 40,
  },
  {
    name: "NVMe",
    optionCode: "storage-nvme",
    description: "Higher-throughput NVMe storage for workloads that need faster I/O.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 100,
    pricePerUnitMonthly: 0.0315,
    pricePerUnitYearly: 0.378,
    unitLabel: "GB",
    minQuantity: 100,
    quantityStep: 50,
    sortOrder: 50,
  },
];

const serverImageAddonTemplates = [
  {
    name: "Ubuntu",
    optionCode: "image-ubuntu",
    description: "Ubuntu LTS server image.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 60,
  },
  {
    name: "Custom Images",
    optionCode: "image-custom",
    description: "Bring a prepared custom image for deployment.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 70,
  },
  {
    name: "Windows Server",
    optionCode: "image-windows-server",
    description: "Licensed Windows Server image.",
    monthlyPrice: 19.1,
    yearlyPrice: 229.2,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 80,
  },
  {
    name: "cPanel",
    optionCode: "image-cpanel",
    description: "cPanel image with the required management licensing.",
    monthlyPrice: 27.5,
    yearlyPrice: 330,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 90,
  },
  {
    name: "RHEL Variants",
    optionCode: "image-rhel",
    description: "RHEL-compatible variants for enterprise-focused deployments.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 100,
  },
  {
    name: "Plesk + Linux",
    optionCode: "image-plesk-linux",
    description: "Plesk on Linux with the required control-panel licensing.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 110,
  },
];

export const addonSeeds = [
  {
    name: "Priority Escalation",
    categorySlug: "vps",
    description: "Faster response targets and dedicated operational escalation.",
    monthlyPrice: 20,
    yearlyPrice: 240,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-priority-escalation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vps",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vds",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Extra Workflow Revision Pack",
    categorySlug: "workflows",
    description: "Additional workflow refinement and optimization hours.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-workflow-revisions",
    isActive: true,
    sortOrder: 1,
  },
  ...serverCommerceCategorySlugs.flatMap((categorySlug) =>
    [...serverRegionAddonTemplates, ...serverStorageAddonTemplates, ...serverImageAddonTemplates].map((addon) => ({
      ...addon,
      categorySlug,
      isActive: true,
    })),
  ),
];

export const paymentSettingSeed = {
  title: "Primary Manual Payment",
  qrCodeImageUrl: "",
  paymentLink: "",
  instructions:
    "Scan the QR code or use the fallback payment link, then submit your payment reference code so our team can verify it.",
  isActive: true,
  supportedFor: [
    "vps",
    "vds",
    "ai-servers",
    "vicidial",
    "workflows",
    "ai-solutions",
    "development-support",
    "cybersecurity",
  ],
};

export const serviceMarketingContent = {
  vps: {
    headline: "Managed VPS for businesses that want hosting without operational overhead.",
    body: "Every VPS plan is operated by the ElevenOrbits team with monitoring, maintenance, and support built in.",
  },
  vds: {
    headline: "Managed VDS with dedicated resources and operational ownership.",
    body: "Use VDS when you need stronger resource isolation while keeping infrastructure management off your team.",
  },
  "ai-servers": {
    headline: "AI-ready infrastructure with managed deployment and support.",
    body: "Run inference or private-model workloads on managed compute while ElevenOrbits operates the platform.",
  },
  vicidial: {
    headline: "Vicidial management subscriptions for reliable call-center operations.",
    body: "We handle updates, tuning, SIP coordination, and support workflows so your agents stay focused.",
  },
  workflows: {
    headline: "Workflow automation on n8n with integrated AI services.",
    body: "Build dependable automations with managed integration, orchestration, and AI-assisted delivery.",
  },
  "ai-solutions": {
    headline: "AI products and managed APIs delivered with operational support.",
    body: "Use ElevenOrbits for managed AI product rollout, prompt operations, and private-model support.",
  },
  "development-support": {
    headline: "Managed support coverage for teams that need technical execution help.",
    body: "Use recurring support plans for implementation help, issue handling, and change coordination.",
  },
  cybersecurity: {
    headline: "Managed cybersecurity services for hosting, applications, and operational risk.",
    body: "Protect hosted systems with managed hardening, monitoring, incident coordination, and security reviews.",
  },
};
