const managedOps = [
  "Managed operations coverage",
  "24/7 operational oversight",
  "Ticketed support and change handling",
];

export const serviceCategories = [
  {
    name: "Managed VPS",
    slug: "vps",
    description: "Production-ready managed virtual private servers for business workloads.",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Managed VDS",
    slug: "vds",
    description: "Higher-isolation managed virtual dedicated servers with dedicated resources.",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Servers",
    slug: "ai-servers",
    description: "Managed GPU and AI compute nodes for inference, training, and private deployments.",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Vicidial Management",
    slug: "vicidial",
    description: "Managed call-center dialer operations, tuning, and lifecycle support.",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Workflow Automation",
    slug: "workflows",
    description: "Managed n8n automation, orchestration, and AI-assisted workflow delivery.",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "AI Solutions",
    slug: "ai-solutions",
    description: "Managed AI products, APIs, agents, and deployment guidance.",
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Development Support",
    slug: "development-support",
    description: "Technical support coverage, implementation help, and managed change support.",
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Managed hardening, monitoring, and security response coverage.",
    isActive: true,
    sortOrder: 8,
  },
];

export const serviceFamilies = [
  {
    name: "Servers",
    description: "Managed compute foundations for hosted applications and business systems.",
    pageSlug: "managed-servers",
    categorySlugs: ["vps", "vds"],
    includes: ["VPS", "VDS"],
    techHighlights: ["KVM / Proxmox", "Ubuntu / AlmaLinux", "Nginx / Apache", "Managed backups"],
  },
  {
    name: "Call Centers",
    description: "Dialer operations, support workflows, and service coordination for active teams.",
    pageSlug: "voip-services",
    categorySlugs: ["vicidial", "development-support"],
    includes: ["Vicidial", "Support"],
    techHighlights: ["Vicidial", "Asterisk", "SIP routing", "Operational runbooks"],
  },
  {
    name: "AI Services",
    description: "AI-ready infrastructure, automation layers, and managed model services.",
    pageSlug: "ai-services",
    categorySlugs: ["ai-servers", "workflows", "ai-solutions"],
    includes: ["AI Servers", "Workflow Automation", "AI Solutions"],
    techHighlights: ["GPU compute", "n8n", "DeepSeek", "Clawbot"],
  },
  {
    name: "Cybersecurity",
    description: "Managed security posture hardening and incident readiness for hosted systems.",
    pageSlug: "cybersecurity-services",
    categorySlugs: ["cybersecurity"],
    includes: ["Basic", "Premium", "Platinum"],
    techHighlights: ["WAF", "SIEM", "EDR", "Patch governance"],
  },
];

export const serviceVerticals = [
  {
    slug: "managed-servers",
    name: "Managed Servers",
    shortName: "Servers",
    eyebrow: "Managed VPS and VDS",
    title: "Managed server hosting for businesses that need uptime, support, and operational ownership.",
    description:
      "ElevenOrbits provides managed VPS and VDS services for production websites, business systems, private applications, and hosted operations that need real support behind the infrastructure.",
    seoTitle: "Managed Servers, VPS and VDS Hosting | ElevenOrbits",
    seoDescription:
      "Managed VPS and VDS hosting from ElevenOrbits with provisioning, monitoring, server hardening, backups, support, and renewal management.",
    categorySlugs: ["vps", "vds"],
    primaryKeyword: "managed servers",
    keywords: ["managed VPS", "managed VDS", "business server hosting", "managed infrastructure", "server management"],
    audience: ["SaaS teams", "business websites", "call centers", "agencies", "internal operations"],
    outcomes: [
      "Provisioned VPS and VDS environments with clear handoff notes.",
      "Managed operating system, web server, firewall, and backup baseline.",
      "Support tickets and service history attached to the customer account.",
      "Recurring billing and wallet-based renewals handled through the portal.",
    ],
    process: [
      "Choose a managed VPS or VDS plan.",
      "Configure region, storage, image, and operational add-ons where available.",
      "Submit payment and wait for verification.",
      "Receive managed service access after ElevenOrbits provisions the environment.",
    ],
    faqs: [
      {
        question: "What is included in ElevenOrbits managed server hosting?",
        answer:
          "Managed server hosting includes provisioning, baseline hardening, monitoring, support routing, maintenance coordination, and renewal management through the customer portal.",
      },
      {
        question: "Should I choose managed VPS or managed VDS?",
        answer:
          "Managed VPS is a strong fit for standard websites and applications. Managed VDS is better when you need stronger isolation, dedicated resources, and more predictable performance.",
      },
      {
        question: "Can ElevenOrbits help migrate an existing server?",
        answer:
          "Yes. Migration planning can be handled through sales or support so the target environment, access details, and cutover steps are defined before work begins.",
      },
    ],
  },
  {
    slug: "ai-services",
    name: "AI Services",
    shortName: "AI",
    eyebrow: "AI infrastructure and solutions",
    title: "Managed AI services for private deployments, AI servers, APIs, and workflow automation.",
    description:
      "ElevenOrbits delivers AI servers, managed DeepSeek services, workflow automation, and AI product rollout support for teams that need practical AI systems instead of disconnected experiments.",
    seoTitle: "Managed AI Services, AI Servers and Automation | ElevenOrbits",
    seoDescription:
      "Managed AI services from ElevenOrbits covering AI servers, DeepSeek API access, private model deployment, AI workflows, and automation support.",
    categorySlugs: ["ai-servers", "ai-solutions", "workflows"],
    primaryKeyword: "managed AI services",
    keywords: ["AI servers", "DeepSeek services", "AI automation", "private AI deployment", "managed AI infrastructure"],
    audience: ["AI product teams", "automation teams", "support operations", "data-driven businesses", "technical founders"],
    outcomes: [
      "GPU-ready or private model infrastructure aligned to the workload.",
      "Managed API, prompt, and workflow operations support.",
      "AI-assisted automation connected to business systems.",
      "Clear support and escalation path after deployment.",
    ],
    process: [
      "Select AI servers, AI solutions, or workflow automation.",
      "Define model, API, workflow, or integration requirements.",
      "Confirm the deployment path and commercial plan.",
      "Operate the AI service through the ElevenOrbits support and billing flow.",
    ],
    faqs: [
      {
        question: "What AI services does ElevenOrbits provide?",
        answer:
          "ElevenOrbits provides managed AI servers, DeepSeek API access, private model deployment support, AI workflow automation, and AI product rollout assistance.",
      },
      {
        question: "Can AI services connect with existing business tools?",
        answer:
          "Yes. Workflow automation can connect CRMs, support desks, forms, APIs, webhooks, and other business tools depending on the scope and integration access.",
      },
      {
        question: "Do I need my own AI infrastructure team?",
        answer:
          "No. The service is designed for teams that want managed AI infrastructure and implementation support without hiring a dedicated internal operations team first.",
      },
    ],
  },
  {
    slug: "voip-services",
    name: "VoIP and Vicidial Services",
    shortName: "VoIP",
    eyebrow: "Call center operations",
    title: "Managed VoIP and Vicidial services for call centers that need stable dialer operations.",
    description:
      "ElevenOrbits supports Vicidial, Asterisk, SIP routing, queue review, dialer tuning, and call-center operations through recurring managed service plans.",
    seoTitle: "Managed VoIP and Vicidial Services | ElevenOrbits",
    seoDescription:
      "Managed VoIP and Vicidial services for call centers, including Asterisk support, SIP routing, dialer tuning, queue review, and operational support.",
    categorySlugs: ["vicidial", "development-support"],
    primaryKeyword: "managed VoIP services",
    keywords: ["Vicidial management", "VoIP support", "Asterisk support", "call center dialer", "SIP routing"],
    audience: ["call centers", "sales teams", "support teams", "BPO operations", "outbound dialing teams"],
    outcomes: [
      "Vicidial and Asterisk operations handled by a managed support team.",
      "Queue, SIP, and routing issues tracked through a support workflow.",
      "Recurring support plans sized for small and growing call centers.",
      "Technical changes coordinated with business impact in mind.",
    ],
    process: [
      "Choose a Vicidial management plan.",
      "Share current dialer, SIP, queue, and operational context.",
      "Let the team review setup and support requirements.",
      "Use support tickets for ongoing dialer and VoIP operations.",
    ],
    faqs: [
      {
        question: "Does ElevenOrbits manage Vicidial systems?",
        answer:
          "Yes. ElevenOrbits offers recurring Vicidial management plans for maintenance, tuning, support routing, SIP coordination, and operational issue handling.",
      },
      {
        question: "Can you help with SIP and Asterisk issues?",
        answer:
          "Yes. VoIP support can include SIP routing, Asterisk-related troubleshooting, dialer behavior review, and coordination around call-center service quality.",
      },
      {
        question: "Is VoIP support available as a monthly service?",
        answer:
          "Yes. Vicidial management plans are available as monthly managed services, with higher-touch support available for larger operations.",
      },
    ],
  },
  {
    slug: "cybersecurity-services",
    name: "Cybersecurity Services",
    shortName: "Security",
    eyebrow: "Managed security operations",
    title: "Managed cybersecurity services for hosted systems, applications, and operational risk.",
    description:
      "ElevenOrbits helps businesses strengthen hosted environments with hardening, monitoring, WAF tuning, patch governance, incident coordination, and security review cadence.",
    seoTitle: "Managed Cybersecurity Services | ElevenOrbits",
    seoDescription:
      "Managed cybersecurity services from ElevenOrbits including hardening, monitoring, WAF tuning, SIEM guidance, patch governance, and incident response coordination.",
    categorySlugs: ["cybersecurity"],
    primaryKeyword: "managed cybersecurity services",
    keywords: ["cybersecurity services", "managed security", "server hardening", "WAF tuning", "incident response"],
    audience: ["hosted businesses", "SaaS platforms", "ecommerce teams", "server owners", "operations leaders"],
    outcomes: [
      "Baseline security hardening for hosted systems.",
      "Security alert triage and operational response coordination.",
      "WAF, firewall, patch, and access-control review.",
      "Executive-level risk summaries available on premium plans.",
    ],
    process: [
      "Select the security coverage level.",
      "Review current hosting, application, access, and risk context.",
      "Apply hardening, monitoring, and operational response workflows.",
      "Continue with recurring posture reviews and incident coordination.",
    ],
    faqs: [
      {
        question: "What does managed cybersecurity include?",
        answer:
          "Managed cybersecurity can include baseline hardening, firewall and WAF review, alert triage, incident coordination, patch governance, and recurring security posture review.",
      },
      {
        question: "Is this a replacement for compliance certification?",
        answer:
          "No. ElevenOrbits managed cybersecurity improves operational security posture, but formal compliance certification requires a dedicated audit and compliance scope.",
      },
      {
        question: "Can cybersecurity be added to managed servers?",
        answer:
          "Yes. Cybersecurity services can complement managed VPS, VDS, AI servers, and other hosted systems that need stronger hardening and response coverage.",
      },
    ],
  },
  {
    slug: "workflow-automation",
    name: "Workflow Automation",
    shortName: "Automation",
    eyebrow: "n8n and AI workflows",
    title: "Workflow automation services for teams that want connected operations and AI-assisted execution.",
    description:
      "ElevenOrbits builds and manages workflow automation across apps, webhooks, APIs, customer operations, and AI-assisted business processes.",
    seoTitle: "Workflow Automation and n8n Services | ElevenOrbits",
    seoDescription:
      "Workflow automation services using n8n, APIs, webhooks, and AI integrations for connected operations, support workflows, and business process automation.",
    categorySlugs: ["workflows"],
    primaryKeyword: "workflow automation services",
    keywords: ["n8n automation", "AI workflows", "business automation", "webhook automation", "API integrations"],
    audience: ["operations teams", "founders", "support teams", "sales teams", "agencies"],
    outcomes: [
      "Automated workflows connecting the tools your team already uses.",
      "AI-assisted steps for routing, summarization, drafting, and classification.",
      "Operational monitoring and revision support on managed plans.",
      "Clear ownership for integration changes and workflow reliability.",
    ],
    process: [
      "Identify the business process to automate.",
      "Choose a workflow plan or request enterprise scoping.",
      "Connect apps, APIs, webhooks, and AI services.",
      "Run and improve workflows through a managed support cycle.",
    ],
    faqs: [
      {
        question: "What can ElevenOrbits automate?",
        answer:
          "ElevenOrbits can automate lead routing, support handoffs, notifications, reporting, CRM updates, data movement, AI summaries, and other API-based workflows.",
      },
      {
        question: "Do you use n8n for workflow automation?",
        answer:
          "Yes. n8n is one of the supported workflow orchestration tools, alongside APIs, webhooks, and AI service integrations.",
      },
      {
        question: "Can automation include AI?",
        answer:
          "Yes. AI can be added for classification, summarization, drafting, decision support, and workflow routing where it is suitable for the process.",
      },
    ],
  },
  {
    slug: "managed-it-support",
    name: "Managed IT and Development Support",
    shortName: "IT Support",
    eyebrow: "Technical support coverage",
    title: "Managed IT and development support for teams that need reliable technical execution.",
    description:
      "ElevenOrbits provides recurring support coverage, implementation help, troubleshooting, change coordination, and managed technical assistance for active business systems.",
    seoTitle: "Managed IT and Development Support | ElevenOrbits",
    seoDescription:
      "Managed IT and development support from ElevenOrbits for troubleshooting, implementation help, change coordination, technical support, and operational execution.",
    categorySlugs: ["development-support"],
    primaryKeyword: "managed IT support",
    keywords: ["managed IT support", "development support", "technical support", "implementation help", "change coordination"],
    audience: ["small businesses", "SaaS teams", "agencies", "operations teams", "technical founders"],
    outcomes: [
      "Recurring technical support with clear ticket ownership.",
      "Implementation help for infrastructure, applications, and workflow changes.",
      "Support plans that scale from basic coverage to custom engineering help.",
      "Operational notes and handoffs tied to the customer account.",
    ],
    process: [
      "Choose a support plan or request a custom support scope.",
      "Share systems, priorities, access process, and support expectations.",
      "Use tickets for issues, changes, and operational support requests.",
      "Review recurring needs and expand coverage when needed.",
    ],
    faqs: [
      {
        question: "What is included in managed IT and development support?",
        answer:
          "Support can include troubleshooting, implementation assistance, infrastructure changes, release coordination, application support, and recurring technical help.",
      },
      {
        question: "Can support be used with other ElevenOrbits services?",
        answer:
          "Yes. Development support can complement managed servers, AI services, cybersecurity, VoIP, and workflow automation.",
      },
      {
        question: "Is advanced support custom scoped?",
        answer:
          "Yes. Advanced development support is scoped around the systems, change volume, and technical requirements of the customer.",
      },
    ],
  },
];

export function getServiceVertical(slug) {
  return serviceVerticals.find((vertical) => vertical.slug === slug);
}

export const productPlanSeeds = [
  {
    name: "Basic Managed VPS",
    slug: "basic-managed-vps",
    categorySlug: "vps",
    description: "Entry managed VPS for websites, apps, and low-risk production services.",
    monthlyPrice: 100,
    yearlyPrice: 960,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "OS hardening and patching", "1 managed environment"],
    techStack: ["Ubuntu / AlmaLinux", "Nginx / Apache", "Managed firewall"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Pro Managed VPS",
    slug: "pro-managed-vps",
    categorySlug: "vps",
    description: "Managed VPS with more headroom for scaling applications and operations.",
    monthlyPrice: 150,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Advanced support routing", "Performance review"],
    techStack: ["Ubuntu / AlmaLinux", "Docker", "Nginx", "Daily backup rotation"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$150/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Elite Managed VPS",
    slug: "elite-managed-vps",
    categorySlug: "vps",
    description: "Premium VPS operations with tighter escalation and managed service coverage.",
    monthlyPrice: 200,
    yearlyPrice: 1920,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Dedicated escalation channel", "Priority maintenance window"],
    techStack: ["Ubuntu / AlmaLinux", "Container orchestration", "WAF rules", "Priority monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$200/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Balanced Managed VDS",
    slug: "balanced-managed-vds",
    categorySlug: "vds",
    description: "Dedicated-resource VDS for stable workloads needing stronger isolation.",
    monthlyPrice: 140,
    yearlyPrice: 1512,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Dedicated vCPU allocation", "Managed baseline tuning"],
    techStack: ["KVM / Proxmox", "Ubuntu / Debian", "Managed snapshots"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$140/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Business Managed VDS",
    slug: "business-managed-vds",
    categorySlug: "vds",
    description: "Business VDS with stronger performance and managed scaling guidance.",
    monthlyPrice: 220,
    yearlyPrice: 2376,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Managed scaling review", "Capacity planning assistance"],
    techStack: ["KVM / Proxmox", "AlmaLinux / Ubuntu", "Managed firewall and backups"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$220/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Enterprise Managed VDS",
    slug: "enterprise-managed-vds",
    categorySlug: "vds",
    description: "High-capacity managed VDS for heavier business systems and bespoke requirements.",
    monthlyPrice: 320,
    yearlyPrice: 3456,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority change coordination", "Dedicated technical planning"],
    techStack: ["KVM / Proxmox", "Load-balanced services", "Managed backup retention"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$320/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "AI Server Starter",
    slug: "ai-server-starter",
    categorySlug: "ai-servers",
    description: "Managed GPU-ready server delivery for small inference and model-serving workloads.",
    monthlyPrice: 260,
    yearlyPrice: 2808,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "GPU environment setup", "Inference deployment support"],
    techStack: ["CUDA-ready GPU node", "PyTorch / vLLM", "Docker", "Model monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$260/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "AI Server Scale",
    slug: "ai-server-scale",
    categorySlug: "ai-servers",
    description: "Managed AI infrastructure for growing internal or customer-facing AI services.",
    monthlyPrice: 420,
    yearlyPrice: 4536,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Model rollout support", "Operational performance reviews"],
    techStack: ["GPU cluster node", "Kubernetes / Docker", "Observability stack", "Private model serving"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$420/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Server Enterprise",
    slug: "ai-server-enterprise",
    categorySlug: "ai-servers",
    description: "Enterprise AI compute deployment with custom architecture and operational planning.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Dedicated rollout plan", "Private infrastructure design", "Custom security controls"],
    techStack: ["GPU clusters", "Private networking", "Registry and artifact controls", "Custom observability"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Starter Vicidial Management",
    slug: "starter-vicidial-management",
    categorySlug: "vicidial",
    description: "Managed Vicidial support for smaller calling teams.",
    monthlyPrice: 50,
    yearlyPrice: 600,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Routine maintenance", "Queue review support"],
    techStack: ["Vicidial", "Asterisk", "SIP trunk setup"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$50/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Growth Vicidial Management",
    slug: "growth-vicidial-management",
    categorySlug: "vicidial",
    description: "Broader dialer management for growing call-center operations.",
    monthlyPrice: 80,
    yearlyPrice: 960,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Performance tuning", "Priority support queue"],
    techStack: ["Vicidial", "Asterisk", "Call recording review", "SIP routing"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$80/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Premium Vicidial Management",
    slug: "premium-vicidial-management",
    categorySlug: "vicidial",
    description: "High-touch management for larger Vicidial and call-center operations.",
    monthlyPrice: 100,
    yearlyPrice: 1200,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Advanced routing review", "Priority escalation"],
    techStack: ["Vicidial", "Asterisk", "SIP routing", "QA workflow support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Workflow Starter",
    slug: "workflow-starter",
    categorySlug: "workflows",
    description: "Managed n8n workflow automation with a focused app footprint.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: ["3 integrated apps", ...managedOps, "AI workflow guidance"],
    techStack: ["n8n", "Webhook orchestration", "DeepSeek / OpenAI integration"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Workflow Growth",
    slug: "workflow-growth",
    categorySlug: "workflows",
    description: "Expanded workflow automation with more integrations and revision capacity.",
    monthlyPrice: 75,
    yearlyPrice: 900,
    yearlyDiscountPercent: 0,
    features: ["5 integrated apps", ...managedOps, "Monitoring and revisions"],
    techStack: ["n8n", "Webhook routing", "Vector / AI integrations", "Monitoring"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$75/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Workflow Enterprise",
    slug: "workflow-enterprise",
    categorySlug: "workflows",
    description: "Enterprise automation architecture with custom integrations and operational support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom app integrations", "Solution architecture", "Dedicated support"],
    techStack: ["n8n", "Custom APIs", "Queue / event design", "Governed deployment"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "automation",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Clawbot",
    slug: "clawbot",
    categorySlug: "ai-solutions",
    description: "Deploy and manage Clawbot-based AI workflows and customer-facing automation.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Managed rollout", "Prompt operations support", "Business automation advisory"],
    techStack: ["Clawbot", "Prompt operations", "Workflow integrations"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "DeepSeek API Access",
    slug: "deepseek-api-access",
    categorySlug: "ai-solutions",
    description: "Managed DeepSeek API access, guardrails, and implementation support.",
    monthlyPrice: 120,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Usage guidance", "Integration support"],
    techStack: ["DeepSeek API", "Usage policy controls", "Integration support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$120/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Open-Source DeepSeek Services",
    slug: "open-source-deepseek-services",
    categorySlug: "ai-solutions",
    description: "Managed open-source DeepSeek deployment and private model service support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Model hosting guidance", "Ops and scaling support", "Custom deployment"],
    techStack: ["Open-source DeepSeek", "vLLM / Ollama", "Private deployment controls"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Managed Support Basic",
    slug: "managed-support-basic",
    categorySlug: "development-support",
    description: "Recurring support coverage for operations teams needing hands-on technical help.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Monthly support allocation", "Ticket support"],
    techStack: ["Ticket queue support", "Runbook execution", "Infrastructure troubleshooting"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "support",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Advanced Development Support",
    slug: "advanced-development-support",
    categorySlug: "development-support",
    description: "Managed implementation and technical support for more complex change requests.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom engineering support", "Architecture review", "Priority coordination"],
    techStack: ["Application support", "Release coordination", "Architecture guidance"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "support",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Basic",
    slug: "cybersecurity-basic",
    categorySlug: "cybersecurity",
    description: "Foundational security hardening and routine monitoring for hosted systems.",
    monthlyPrice: 90,
    yearlyPrice: 972,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Baseline hardening checklist", "Security alert triage"],
    techStack: ["Firewall policy review", "OS hardening", "Fail2Ban / WAF"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$90/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Cybersecurity Premium",
    slug: "cybersecurity-premium",
    categorySlug: "cybersecurity",
    description: "Broader monitoring, response coordination, and managed hardening coverage.",
    monthlyPrice: 170,
    yearlyPrice: 1836,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "WAF tuning", "Incident response coordination", "Monthly posture review"],
    techStack: ["WAF / reverse proxy", "SIEM ingestion", "Patch governance"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$170/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Platinum",
    slug: "cybersecurity-platinum",
    categorySlug: "cybersecurity",
    description: "Premium managed security operations with faster response and deeper review cadence.",
    monthlyPrice: 280,
    yearlyPrice: 3024,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority incident handling", "Security change planning", "Executive risk summary"],
    techStack: ["WAF", "SIEM", "EDR guidance", "Response playbooks"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$280/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 3,
  },
];

const serverCommerceCategorySlugs = ["vps", "vds"];

const serverRegionAddonTemplates = [
  {
    name: "European Union",
    optionCode: "region-eu",
    description: "Low-latency European deployment region.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 10,
  },
  {
    name: "United States (West)",
    optionCode: "region-us-west",
    description: "West coast region for American traffic routing.",
    monthlyPrice: 2.2,
    yearlyPrice: 26.4,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 20,
  },
  {
    name: "Asia (Singapore)",
    optionCode: "region-asia-singapore",
    description: "APAC-friendly region with strong Southeast Asia coverage.",
    monthlyPrice: 4.4,
    yearlyPrice: 52.8,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 30,
  },
];

const serverStorageAddonTemplates = [
  {
    name: "SSD",
    optionCode: "storage-ssd",
    description: "General-purpose SSD storage with a generous included base allocation.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 200,
    pricePerUnitMonthly: 0.012,
    pricePerUnitYearly: 0.144,
    unitLabel: "GB",
    minQuantity: 200,
    quantityStep: 50,
    sortOrder: 40,
  },
  {
    name: "NVMe",
    optionCode: "storage-nvme",
    description: "Higher-throughput NVMe storage for workloads that need faster I/O.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 100,
    pricePerUnitMonthly: 0.0315,
    pricePerUnitYearly: 0.378,
    unitLabel: "GB",
    minQuantity: 100,
    quantityStep: 50,
    sortOrder: 50,
  },
];

const serverImageAddonTemplates = [
  {
    name: "Ubuntu",
    optionCode: "image-ubuntu",
    description: "Ubuntu LTS server image.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 60,
  },
  {
    name: "Custom Images",
    optionCode: "image-custom",
    description: "Bring a prepared custom image for deployment.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 70,
  },
  {
    name: "Windows Server",
    optionCode: "image-windows-server",
    description: "Licensed Windows Server image.",
    monthlyPrice: 19.1,
    yearlyPrice: 229.2,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 80,
  },
  {
    name: "cPanel",
    optionCode: "image-cpanel",
    description: "cPanel image with the required management licensing.",
    monthlyPrice: 27.5,
    yearlyPrice: 330,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 90,
  },
  {
    name: "RHEL Variants",
    optionCode: "image-rhel",
    description: "RHEL-compatible variants for enterprise-focused deployments.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 100,
  },
  {
    name: "Plesk + Linux",
    optionCode: "image-plesk-linux",
    description: "Plesk on Linux with the required control-panel licensing.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 110,
  },
];

export const addonSeeds = [
  {
    name: "Priority Escalation",
    categorySlug: "vps",
    description: "Faster response targets and dedicated operational escalation.",
    monthlyPrice: 20,
    yearlyPrice: 240,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-priority-escalation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vps",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vds",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Extra Workflow Revision Pack",
    categorySlug: "workflows",
    description: "Additional workflow refinement and optimization hours.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-workflow-revisions",
    isActive: true,
    sortOrder: 1,
  },
  ...serverCommerceCategorySlugs.flatMap((categorySlug) =>
    [...serverRegionAddonTemplates, ...serverStorageAddonTemplates, ...serverImageAddonTemplates].map((addon) => ({
      ...addon,
      categorySlug,
      isActive: true,
    })),
  ),
];

export const serviceMarketingContent = {
  vps: {
    headline: "Managed VPS for businesses that want hosting without operational overhead.",
    body: "Every VPS plan is operated by the ElevenOrbits team with monitoring, maintenance, and support built in.",
  },
  vds: {
    headline: "Managed VDS with dedicated resources and operational ownership.",
    body: "Use VDS when you need stronger resource isolation while keeping infrastructure management off your team.",
  },
  "ai-servers": {
    headline: "AI-ready infrastructure with managed deployment and support.",
    body: "Run inference or private-model workloads on managed compute while ElevenOrbits operates the platform.",
  },
  vicidial: {
    headline: "Vicidial management subscriptions for reliable call-center operations.",
    body: "We handle updates, tuning, SIP coordination, and support workflows so your agents stay focused.",
  },
  workflows: {
    headline: "Workflow automation on n8n with integrated AI services.",
    body: "Build dependable automations with managed integration, orchestration, and AI-assisted delivery.",
  },
  "ai-solutions": {
    headline: "AI products and managed APIs delivered with operational support.",
    body: "Use ElevenOrbits for managed AI product rollout, prompt operations, and private-model support.",
  },
  "development-support": {
    headline: "Managed support coverage for teams that need technical execution help.",
    body: "Use recurring support plans for implementation help, issue handling, and change coordination.",
  },
  cybersecurity: {
    headline: "Managed cybersecurity services for hosting, applications, and operational risk.",
    body: "Protect hosted systems with managed hardening, monitoring, incident coordination, and security reviews.",
  },
};
