const managedOps = [
  "Managed operations coverage",
  "24/7 operational oversight",
  "Ticketed support and change handling",
];

export const serviceCategories = [
  {
    name: "Managed VPS",
    slug: "vps",
    description: "Production-ready managed virtual private servers for business workloads.",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Managed VDS",
    slug: "vds",
    description: "Higher-isolation managed virtual dedicated servers with dedicated resources.",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Servers",
    slug: "ai-servers",
    description: "Managed GPU and AI compute nodes for inference, training, and private deployments.",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Vicidial Management",
    slug: "vicidial",
    description: "Managed call-center dialer operations, tuning, and lifecycle support.",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Workflow Automation",
    slug: "workflows",
    description: "Managed n8n automation, orchestration, and AI-assisted workflow delivery.",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "AI Solutions",
    slug: "ai-solutions",
    description: "Managed AI products, APIs, agents, and deployment guidance.",
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Development Support",
    slug: "development-support",
    description: "Technical support coverage, implementation help, and managed change support.",
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Cybersecurity",
    slug: "cybersecurity",
    description: "Managed hardening, monitoring, and security response coverage.",
    isActive: true,
    sortOrder: 8,
  },
  {
    name: "Managed CDN",
    slug: "cdn",
    description: "Managed content delivery, caching, image optimization, DDoS protection, and edge performance for high-traffic sites.",
    isActive: true,
    sortOrder: 9,
  },
  {
    name: "Object Storage",
    slug: "object-storage",
    description: "Managed S3-compatible object storage for backups, media, AI datasets, and file distribution.",
    isActive: true,
    sortOrder: 10,
  },
  {
    name: "Hermes AI Hosting",
    slug: "hermes-ai-hosting",
    description: "Managed self-hosted Hermes AI agent VPS plans with one-click install, memory, tools, and private agent operations.",
    isActive: true,
    sortOrder: 11,
  },
  {
    name: "OpenClaw Hosting",
    slug: "openclaw-hosting",
    description: "Managed self-hosted OpenClaw assistant VPS plans for always-on automation, messaging integrations, and private AI workflows.",
    isActive: true,
    sortOrder: 12,
  },
  {
    name: "Nextcloud Hosting",
    slug: "nextcloud-hosting",
    description: "Managed self-hosted Nextcloud plans for private file sync, sharing, backup, calendars, contacts, and collaboration.",
    isActive: true,
    sortOrder: 13,
  },
];

export const serviceFamilies = [
  {
    name: "Managed Cloud",
    description: "Managed VPS, VDS, CDN, object storage, and self-hosted app infrastructure under one operating model.",
    pageSlug: "services",
    categorySlugs: ["vps", "vds", "cdn", "object-storage", "hermes-ai-hosting", "openclaw-hosting", "nextcloud-hosting"],
    includes: ["VPS", "VDS", "CDN", "Object Storage", "Hosted Apps"],
    techHighlights: ["KVM / Proxmox", "S3-compatible storage", "Managed CDN", "Self-hosted apps"],
  },
  {
    name: "Call Centers",
    description: "Dialer operations, support workflows, and service coordination for active teams.",
    pageSlug: "voip-services",
    categorySlugs: ["vicidial", "development-support"],
    includes: ["Vicidial", "Support"],
    techHighlights: ["Vicidial", "Asterisk", "SIP routing", "Operational runbooks"],
  },
  {
    name: "AI Services",
    description: "AI-ready infrastructure, automation layers, and managed model services.",
    pageSlug: "ai-services",
    categorySlugs: ["ai-servers", "workflows", "ai-solutions"],
    includes: ["AI Servers", "Workflow Automation", "AI Solutions"],
    techHighlights: ["GPU compute", "n8n", "DeepSeek", "Clawbot"],
  },
  {
    name: "Cybersecurity",
    description: "Managed security posture hardening and incident readiness for hosted systems.",
    pageSlug: "cybersecurity-services",
    categorySlugs: ["cybersecurity"],
    includes: ["Basic", "Premium", "Platinum"],
    techHighlights: ["WAF", "SIEM", "EDR", "Patch governance"],
  },
];

export const serviceVerticals = [
  {
    slug: "managed-servers",
    name: "Managed Servers",
    shortName: "Servers",
    eyebrow: "Managed VPS and VDS",
    title: "Managed server hosting for businesses that need uptime, support, and operational ownership.",
    description:
      "ElevenOrbits provides managed VPS and VDS services for production websites, business systems, private applications, and hosted operations that need real support behind the infrastructure.",
    seoTitle: "Managed Servers, VPS and VDS Hosting | ElevenOrbits",
    seoDescription:
      "Managed VPS and VDS hosting from ElevenOrbits with provisioning, monitoring, server hardening, backups, support, and renewal management.",
    categorySlugs: ["vps", "vds"],
    primaryKeyword: "managed servers",
    keywords: ["managed VPS", "managed VDS", "business server hosting", "managed infrastructure", "server management"],
    audience: ["SaaS teams", "business websites", "call centers", "agencies", "internal operations"],
    outcomes: [
      "Provisioned VPS and VDS environments with clear handoff notes.",
      "Managed operating system, web server, firewall, and backup baseline.",
      "Support tickets and service history attached to the customer account.",
      "Recurring billing and wallet-based renewals handled through the portal.",
    ],
    process: [
      "Choose a managed VPS or VDS plan.",
      "Configure region, storage, image, and operational add-ons where available.",
      "Submit payment and wait for verification.",
      "Receive managed service access after ElevenOrbits provisions the environment.",
    ],
    faqs: [
      {
        question: "What is included in ElevenOrbits managed server hosting?",
        answer:
          "Managed server hosting includes provisioning, baseline hardening, monitoring, support routing, maintenance coordination, and renewal management through the customer portal.",
      },
      {
        question: "Should I choose managed VPS or managed VDS?",
        answer:
          "Managed VPS is a strong fit for standard websites and applications. Managed VDS is better when you need stronger isolation, dedicated resources, and more predictable performance.",
      },
      {
        question: "Can ElevenOrbits help migrate an existing server?",
        answer:
          "Yes. Migration planning can be handled through sales or support so the target environment, access details, and cutover steps are defined before work begins.",
      },
    ],
  },
  {
    slug: "ai-services",
    name: "AI Services",
    shortName: "AI",
    eyebrow: "AI infrastructure and solutions",
    title: "Managed AI services for private deployments, AI servers, APIs, and workflow automation.",
    description:
      "ElevenOrbits delivers AI servers, managed DeepSeek services, workflow automation, and AI product rollout support for teams that need practical AI systems instead of disconnected experiments.",
    seoTitle: "Managed AI Services, AI Servers and Automation | ElevenOrbits",
    seoDescription:
      "Managed AI services from ElevenOrbits covering AI servers, DeepSeek API access, private model deployment, AI workflows, and automation support.",
    categorySlugs: ["ai-servers", "ai-solutions", "workflows"],
    primaryKeyword: "managed AI services",
    keywords: ["AI servers", "DeepSeek services", "AI automation", "private AI deployment", "managed AI infrastructure"],
    audience: ["AI product teams", "automation teams", "support operations", "data-driven businesses", "technical founders"],
    outcomes: [
      "GPU-ready or private model infrastructure aligned to the workload.",
      "Managed API, prompt, and workflow operations support.",
      "AI-assisted automation connected to business systems.",
      "Clear support and escalation path after deployment.",
    ],
    process: [
      "Select AI servers, AI solutions, or workflow automation.",
      "Define model, API, workflow, or integration requirements.",
      "Confirm the deployment path and commercial plan.",
      "Operate the AI service through the ElevenOrbits support and billing flow.",
    ],
    faqs: [
      {
        question: "What AI services does ElevenOrbits provide?",
        answer:
          "ElevenOrbits provides managed AI servers, DeepSeek API access, private model deployment support, AI workflow automation, and AI product rollout assistance.",
      },
      {
        question: "Can AI services connect with existing business tools?",
        answer:
          "Yes. Workflow automation can connect CRMs, support desks, forms, APIs, webhooks, and other business tools depending on the scope and integration access.",
      },
      {
        question: "Do I need my own AI infrastructure team?",
        answer:
          "No. The service is designed for teams that want managed AI infrastructure and implementation support without hiring a dedicated internal operations team first.",
      },
    ],
  },
  {
    slug: "voip-services",
    name: "VoIP and Vicidial Services",
    shortName: "VoIP",
    eyebrow: "Call center operations",
    title: "Managed VoIP and Vicidial services for call centers that need stable dialer operations.",
    description:
      "ElevenOrbits supports Vicidial, Asterisk, SIP routing, queue review, dialer tuning, and call-center operations through recurring managed service plans.",
    seoTitle: "Managed VoIP and Vicidial Services | ElevenOrbits",
    seoDescription:
      "Managed VoIP and Vicidial services for call centers, including Asterisk support, SIP routing, dialer tuning, queue review, and operational support.",
    categorySlugs: ["vicidial", "development-support"],
    primaryKeyword: "managed VoIP services",
    keywords: ["Vicidial management", "VoIP support", "Asterisk support", "call center dialer", "SIP routing"],
    audience: ["call centers", "sales teams", "support teams", "BPO operations", "outbound dialing teams"],
    outcomes: [
      "Vicidial and Asterisk operations handled by a managed support team.",
      "Queue, SIP, and routing issues tracked through a support workflow.",
      "Recurring support plans sized for small and growing call centers.",
      "Technical changes coordinated with business impact in mind.",
    ],
    process: [
      "Choose a Vicidial management plan.",
      "Share current dialer, SIP, queue, and operational context.",
      "Let the team review setup and support requirements.",
      "Use support tickets for ongoing dialer and VoIP operations.",
    ],
    faqs: [
      {
        question: "Does ElevenOrbits manage Vicidial systems?",
        answer:
          "Yes. ElevenOrbits offers recurring Vicidial management plans for maintenance, tuning, support routing, SIP coordination, and operational issue handling.",
      },
      {
        question: "Can you help with SIP and Asterisk issues?",
        answer:
          "Yes. VoIP support can include SIP routing, Asterisk-related troubleshooting, dialer behavior review, and coordination around call-center service quality.",
      },
      {
        question: "Is VoIP support available as a monthly service?",
        answer:
          "Yes. Vicidial management plans are available as monthly managed services, with higher-touch support available for larger operations.",
      },
    ],
  },
  {
    slug: "cybersecurity-services",
    name: "Cybersecurity Services",
    shortName: "Security",
    eyebrow: "Managed security operations",
    title: "Managed cybersecurity services for hosted systems, applications, and operational risk.",
    description:
      "ElevenOrbits helps businesses strengthen hosted environments with hardening, monitoring, WAF tuning, patch governance, incident coordination, and security review cadence.",
    seoTitle: "Managed Cybersecurity Services | ElevenOrbits",
    seoDescription:
      "Managed cybersecurity services from ElevenOrbits including hardening, monitoring, WAF tuning, SIEM guidance, patch governance, and incident response coordination.",
    categorySlugs: ["cybersecurity"],
    primaryKeyword: "managed cybersecurity services",
    keywords: ["cybersecurity services", "managed security", "server hardening", "WAF tuning", "incident response"],
    audience: ["hosted businesses", "SaaS platforms", "ecommerce teams", "server owners", "operations leaders"],
    outcomes: [
      "Baseline security hardening for hosted systems.",
      "Security alert triage and operational response coordination.",
      "WAF, firewall, patch, and access-control review.",
      "Executive-level risk summaries available on premium plans.",
    ],
    process: [
      "Select the security coverage level.",
      "Review current hosting, application, access, and risk context.",
      "Apply hardening, monitoring, and operational response workflows.",
      "Continue with recurring posture reviews and incident coordination.",
    ],
    faqs: [
      {
        question: "What does managed cybersecurity include?",
        answer:
          "Managed cybersecurity can include baseline hardening, firewall and WAF review, alert triage, incident coordination, patch governance, and recurring security posture review.",
      },
      {
        question: "Is this a replacement for compliance certification?",
        answer:
          "No. ElevenOrbits managed cybersecurity improves operational security posture, but formal compliance certification requires a dedicated audit and compliance scope.",
      },
      {
        question: "Can cybersecurity be added to managed servers?",
        answer:
          "Yes. Cybersecurity services can complement managed VPS, VDS, AI servers, and other hosted systems that need stronger hardening and response coverage.",
      },
    ],
  },
  {
    slug: "edge-storage-services",
    name: "Edge and Storage Services",
    shortName: "Edge and Storage",
    eyebrow: "CDN and object storage",
    title: "Managed CDN and object storage services for fast content delivery, backups, media, and AI data.",
    description:
      "ElevenOrbits provides managed CDN packages and S3-compatible object storage for businesses that need predictable pricing, secure delivery, and operational support around content and data workflows.",
    seoTitle: "Managed CDN and Object Storage Services | ElevenOrbits",
    seoDescription:
      "Managed CDN and S3-compatible object storage from ElevenOrbits with edge caching, image optimization, DDoS protection, predictable storage tiers, and support.",
    categorySlugs: ["cdn", "object-storage"],
    primaryKeyword: "managed CDN and object storage",
    keywords: ["managed CDN", "object storage", "S3-compatible storage", "content delivery network", "cloud storage"],
    audience: ["ecommerce teams", "media-heavy websites", "SaaS platforms", "AI teams", "backup workflows"],
    outcomes: [
      "Faster content delivery through managed CDN caching and optimization.",
      "Predictable storage tiers for backups, media files, datasets, and archives.",
      "Operational support for DNS, caching rules, SSL, S3 credentials, and bucket access.",
      "Security controls including DDoS protection, ACL planning, and access review.",
    ],
    process: [
      "Choose a CDN or Object Storage package.",
      "Share domain, origin, bucket, region, and access requirements.",
      "ElevenOrbits provisions the service and records setup details in the portal.",
      "Use support tickets for cache, storage, migration, access, and policy changes.",
    ],
    faqs: [
      {
        question: "What CDN services does ElevenOrbits offer?",
        answer:
          "ElevenOrbits offers managed CDN packages with unlimited domains, caching rules, image optimization, DDoS protection, analytics on higher plans, and operational support.",
      },
      {
        question: "Is Object Storage S3-compatible?",
        answer:
          "Yes. Object Storage plans are built around S3-compatible workflows so applications, tools, and migration utilities can usually connect with an endpoint and credential change.",
      },
      {
        question: "Can ElevenOrbits help migrate existing media or backup data?",
        answer:
          "Yes. Migration support can be coordinated through the portal using tools such as S3-compatible clients, Rclone, AWS CLI style workflows, or application-level updates.",
      },
    ],
  },
  {
    slug: "self-hosted-app-services",
    name: "Self-Hosted App Services",
    shortName: "Apps",
    eyebrow: "AI agents and private cloud apps",
    title: "Managed self-hosted apps for Hermes AI, OpenClaw, and Nextcloud on private VPS infrastructure.",
    description:
      "ElevenOrbits provisions and operates VPS-backed app hosting for teams that want private AI agents, always-on automation, and self-hosted collaboration without managing the server alone.",
    seoTitle: "Self-Hosted Hermes AI, OpenClaw and Nextcloud Hosting | ElevenOrbits",
    seoDescription:
      "Managed self-hosted app hosting from ElevenOrbits for Hermes AI agents, OpenClaw assistants, and Nextcloud private cloud deployments with VPS resources and portal handoff.",
    categorySlugs: ["hermes-ai-hosting", "openclaw-hosting", "nextcloud-hosting"],
    primaryKeyword: "managed self-hosted app hosting",
    keywords: ["Hermes AI hosting", "OpenClaw hosting", "Nextcloud hosting", "self-hosted AI agent", "managed app VPS"],
    audience: ["AI builders", "small teams", "developers", "private cloud users", "automation-heavy businesses"],
    outcomes: [
      "Private app hosting on a managed VPS with clear resource sizing.",
      "Admin-published app URLs, SSH details, setup notes, and handoff credentials in the customer portal.",
      "Support for always-on AI agents, subagents, integrations, and private collaboration workloads.",
      "Flat monthly pricing without per-token or per-user app charges from ElevenOrbits.",
    ],
    process: [
      "Choose Hermes AI, OpenClaw, or Nextcloud hosting.",
      "Share region, domain, app access, model/provider, user, storage, and integration requirements.",
      "ElevenOrbits provisions the server, installs or validates the app, and publishes access details in the portal.",
      "Use support tickets for upgrades, app handoff, access changes, backup notes, and operational follow-up.",
    ],
    faqs: [
      {
        question: "What self-hosted apps does ElevenOrbits offer?",
        answer:
          "ElevenOrbits offers managed VPS-backed hosting plans for Hermes AI agents, OpenClaw assistants, and Nextcloud private cloud deployments.",
      },
      {
        question: "Will the customer get app access in the portal?",
        answer:
          "Yes. After provisioning, the admin team can publish app URLs, SSH details, usernames, passwords, setup status, and custom handoff notes to the customer's portal.",
      },
      {
        question: "Do these plans include AI model usage?",
        answer:
          "The hosting plan covers the managed VPS and app handoff. Customers can connect supported AI providers or local models depending on the selected app and resources.",
      },
    ],
  },
  {
    slug: "workflow-automation",
    name: "Workflow Automation",
    shortName: "Automation",
    eyebrow: "n8n and AI workflows",
    title: "Workflow automation services for teams that want connected operations and AI-assisted execution.",
    description:
      "ElevenOrbits builds and manages workflow automation across apps, webhooks, APIs, customer operations, and AI-assisted business processes.",
    seoTitle: "Workflow Automation and n8n Services | ElevenOrbits",
    seoDescription:
      "Workflow automation services using n8n, APIs, webhooks, and AI integrations for connected operations, support workflows, and business process automation.",
    categorySlugs: ["workflows"],
    primaryKeyword: "workflow automation services",
    keywords: ["n8n automation", "AI workflows", "business automation", "webhook automation", "API integrations"],
    audience: ["operations teams", "founders", "support teams", "sales teams", "agencies"],
    outcomes: [
      "Automated workflows connecting the tools your team already uses.",
      "AI-assisted steps for routing, summarization, drafting, and classification.",
      "Operational monitoring and revision support on managed plans.",
      "Clear ownership for integration changes and workflow reliability.",
    ],
    process: [
      "Identify the business process to automate.",
      "Choose a workflow plan or request enterprise scoping.",
      "Connect apps, APIs, webhooks, and AI services.",
      "Run and improve workflows through a managed support cycle.",
    ],
    faqs: [
      {
        question: "What can ElevenOrbits automate?",
        answer:
          "ElevenOrbits can automate lead routing, support handoffs, notifications, reporting, CRM updates, data movement, AI summaries, and other API-based workflows.",
      },
      {
        question: "Do you use n8n for workflow automation?",
        answer:
          "Yes. n8n is one of the supported workflow orchestration tools, alongside APIs, webhooks, and AI service integrations.",
      },
      {
        question: "Can automation include AI?",
        answer:
          "Yes. AI can be added for classification, summarization, drafting, decision support, and workflow routing where it is suitable for the process.",
      },
    ],
  },
  {
    slug: "managed-it-support",
    name: "Managed IT and Development Support",
    shortName: "IT Support",
    eyebrow: "Technical support coverage",
    title: "Managed IT and development support for teams that need reliable technical execution.",
    description:
      "ElevenOrbits provides recurring support coverage, implementation help, troubleshooting, change coordination, and managed technical assistance for active business systems.",
    seoTitle: "Managed IT and Development Support | ElevenOrbits",
    seoDescription:
      "Managed IT and development support from ElevenOrbits for troubleshooting, implementation help, change coordination, technical support, and operational execution.",
    categorySlugs: ["development-support"],
    primaryKeyword: "managed IT support",
    keywords: ["managed IT support", "development support", "technical support", "implementation help", "change coordination"],
    audience: ["small businesses", "SaaS teams", "agencies", "operations teams", "technical founders"],
    outcomes: [
      "Recurring technical support with clear ticket ownership.",
      "Implementation help for infrastructure, applications, and workflow changes.",
      "Support plans that scale from basic coverage to custom engineering help.",
      "Operational notes and handoffs tied to the customer account.",
    ],
    process: [
      "Choose a support plan or request a custom support scope.",
      "Share systems, priorities, access process, and support expectations.",
      "Use tickets for issues, changes, and operational support requests.",
      "Review recurring needs and expand coverage when needed.",
    ],
    faqs: [
      {
        question: "What is included in managed IT and development support?",
        answer:
          "Support can include troubleshooting, implementation assistance, infrastructure changes, release coordination, application support, and recurring technical help.",
      },
      {
        question: "Can support be used with other ElevenOrbits services?",
        answer:
          "Yes. Development support can complement managed servers, AI services, cybersecurity, VoIP, and workflow automation.",
      },
      {
        question: "Is advanced support custom scoped?",
        answer:
          "Yes. Advanced development support is scoped around the systems, change volume, and technical requirements of the customer.",
      },
    ],
  },
];

export function getServiceVertical(slug) {
  return serviceVerticals.find((vertical) => vertical.slug === slug);
}

const selfHostedAppPlanSeeds = [
  {
    name: "Hermes AI Personal VPS",
    slug: "hermes-ai-personal-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for one person running a private daily AI assistant.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "4 vCPU cores", "8 GB RAM", "75 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "4 vCPU", "8 GB RAM", "75 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Hermes AI Power User VPS",
    slug: "hermes-ai-power-user-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for daily use across more tools, integrations, and agent sessions.",
    monthlyPrice: 12.96,
    yearlyPrice: 155.52,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "6 vCPU cores", "12 GB RAM", "100 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "6 vCPU", "12 GB RAM", "100 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$12.96/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Hermes AI Team Deployment VPS",
    slug: "hermes-ai-team-deployment-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for small teams with multiple subagents running in parallel.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "12 vCPU cores", "48 GB RAM", "250 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "12 vCPU", "48 GB RAM", "250 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Hermes AI Enterprise Scale VPS",
    slug: "hermes-ai-enterprise-scale-vps",
    categorySlug: "hermes-ai-hosting",
    description: "Managed Hermes Agent VPS for complex pipelines, heavier parallel workloads, and enterprise agent operations.",
    monthlyPrice: 84.67,
    yearlyPrice: 1016.04,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free 1-click Hermes Agent install", "Memory across sessions", "18 vCPU cores", "96 GB RAM", "350 GB NVMe", "Auto Backup available"],
    techStack: ["Hermes Agent", "18 vCPU", "96 GB RAM", "350 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$84.67/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "OpenClaw Personal VPS",
    slug: "openclaw-personal-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for individuals running a private always-on AI assistant.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "4 vCPU cores", "8 GB RAM", "75 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "4 vCPU", "8 GB RAM", "75 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "OpenClaw Power User VPS",
    slug: "openclaw-power-user-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for heavier use across messaging platforms, tools, and workflow integrations.",
    monthlyPrice: 12.96,
    yearlyPrice: 155.52,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "6 vCPU cores", "12 GB RAM", "100 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "6 vCPU", "12 GB RAM", "100 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$12.96/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "OpenClaw Team Deployment VPS",
    slug: "openclaw-team-deployment-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for small teams with advanced automation and multiple workflows.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "12 vCPU cores", "48 GB RAM", "250 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "12 vCPU", "48 GB RAM", "250 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "OpenClaw Enterprise Scale VPS",
    slug: "openclaw-enterprise-scale-vps",
    categorySlug: "openclaw-hosting",
    description: "Managed OpenClaw VPS for complex AI workflows, heavy integrations, and larger automation workloads.",
    monthlyPrice: 84.67,
    yearlyPrice: 1016.04,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed OpenClaw", "Always-on automation", "16 vCPU cores", "64 GB RAM", "500 GB NVMe", "Full data control"],
    techStack: ["OpenClaw", "16 vCPU", "64 GB RAM", "500 GB NVMe"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$84.67/mo",
    serviceType: "self_hosted_ai_agent",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "Nextcloud Starter",
    slug: "nextcloud-starter",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for individuals, families, or small teams syncing files, calendars, and contacts.",
    monthlyPrice: 9.5,
    yearlyPrice: 114,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "4 vCPU cores", "8 GB RAM", "150 GB SSD / 75 GB NVMe", "Full data control"],
    techStack: ["Nextcloud", "4 vCPU", "8 GB RAM", "150 GB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$9.50/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Nextcloud Large Media Libraries",
    slug: "nextcloud-large-media-libraries",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting with 1 TB storage for creators, media libraries, backups, and large file sharing.",
    monthlyPrice: 24.19,
    yearlyPrice: 290.28,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "6 vCPU cores", "18 GB RAM", "1 TB SSD", "Full data control"],
    techStack: ["Nextcloud", "6 vCPU", "18 GB RAM", "1 TB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$24.19/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Nextcloud Business Needs",
    slug: "nextcloud-business-needs",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for growing businesses with active users, apps, sharing, and collaboration.",
    monthlyPrice: 43.2,
    yearlyPrice: 518.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "12 vCPU cores", "48 GB RAM", "500 GB SSD / 250 GB NVMe", "Full data control"],
    techStack: ["Nextcloud", "12 vCPU", "48 GB RAM", "500 GB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.20/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Nextcloud Ultimate Media Server",
    slug: "nextcloud-ultimate-media-server",
    categorySlug: "nextcloud-hosting",
    description: "Managed Nextcloud hosting for extensive media collections, streaming, backups, and large collaboration spaces.",
    monthlyPrice: 64.08,
    yearlyPrice: 768.96,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Free pre-installed Nextcloud", "Unlimited users", "14 vCPU cores", "50 GB RAM", "1.4 TB SSD", "1 Gbit/s port"],
    techStack: ["Nextcloud", "14 vCPU", "50 GB RAM", "1.4 TB SSD"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$64.08/mo",
    serviceType: "self_hosted_collaboration",
    isActive: true,
    sortOrder: 4,
  },
];

export const productPlanSeeds = [
  {
    name: "Basic Managed VPS",
    slug: "basic-managed-vps",
    categorySlug: "vps",
    description: "Entry managed VPS for websites, apps, and low-risk production services.",
    monthlyPrice: 100,
    yearlyPrice: 960,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "OS hardening and patching", "1 managed environment"],
    techStack: ["Ubuntu / AlmaLinux", "Nginx / Apache", "Managed firewall"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Pro Managed VPS",
    slug: "pro-managed-vps",
    categorySlug: "vps",
    description: "Managed VPS with more headroom for scaling applications and operations.",
    monthlyPrice: 150,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Advanced support routing", "Performance review"],
    techStack: ["Ubuntu / AlmaLinux", "Docker", "Nginx", "Daily backup rotation"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$150/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Elite Managed VPS",
    slug: "elite-managed-vps",
    categorySlug: "vps",
    description: "Premium VPS operations with tighter escalation and managed service coverage.",
    monthlyPrice: 200,
    yearlyPrice: 1920,
    yearlyDiscountPercent: 20,
    features: [...managedOps, "Dedicated escalation channel", "Priority maintenance window"],
    techStack: ["Ubuntu / AlmaLinux", "Container orchestration", "WAF rules", "Priority monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$200/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Balanced Managed VDS",
    slug: "balanced-managed-vds",
    categorySlug: "vds",
    description: "Dedicated-resource VDS for stable workloads needing stronger isolation.",
    monthlyPrice: 140,
    yearlyPrice: 1512,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Dedicated vCPU allocation", "Managed baseline tuning"],
    techStack: ["KVM / Proxmox", "Ubuntu / Debian", "Managed snapshots"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$140/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Business Managed VDS",
    slug: "business-managed-vds",
    categorySlug: "vds",
    description: "Business VDS with stronger performance and managed scaling guidance.",
    monthlyPrice: 220,
    yearlyPrice: 2376,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Managed scaling review", "Capacity planning assistance"],
    techStack: ["KVM / Proxmox", "AlmaLinux / Ubuntu", "Managed firewall and backups"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$220/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Enterprise Managed VDS",
    slug: "enterprise-managed-vds",
    categorySlug: "vds",
    description: "High-capacity managed VDS for heavier business systems and bespoke requirements.",
    monthlyPrice: 320,
    yearlyPrice: 3456,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority change coordination", "Dedicated technical planning"],
    techStack: ["KVM / Proxmox", "Load-balanced services", "Managed backup retention"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$320/mo",
    serviceType: "managed_infrastructure",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "AI Server Starter",
    slug: "ai-server-starter",
    categorySlug: "ai-servers",
    description: "Managed GPU-ready server delivery for small inference and model-serving workloads.",
    monthlyPrice: 260,
    yearlyPrice: 2808,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "GPU environment setup", "Inference deployment support"],
    techStack: ["CUDA-ready GPU node", "PyTorch / vLLM", "Docker", "Model monitoring"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$260/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "AI Server Scale",
    slug: "ai-server-scale",
    categorySlug: "ai-servers",
    description: "Managed AI infrastructure for growing internal or customer-facing AI services.",
    monthlyPrice: 420,
    yearlyPrice: 4536,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Model rollout support", "Operational performance reviews"],
    techStack: ["GPU cluster node", "Kubernetes / Docker", "Observability stack", "Private model serving"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$420/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "AI Server Enterprise",
    slug: "ai-server-enterprise",
    categorySlug: "ai-servers",
    description: "Enterprise AI compute deployment with custom architecture and operational planning.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Dedicated rollout plan", "Private infrastructure design", "Custom security controls"],
    techStack: ["GPU clusters", "Private networking", "Registry and artifact controls", "Custom observability"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Starter Vicidial Management",
    slug: "starter-vicidial-management",
    categorySlug: "vicidial",
    description: "Managed Vicidial support for smaller calling teams.",
    monthlyPrice: 50,
    yearlyPrice: 600,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Routine maintenance", "Queue review support"],
    techStack: ["Vicidial", "Asterisk", "SIP trunk setup"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$50/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Growth Vicidial Management",
    slug: "growth-vicidial-management",
    categorySlug: "vicidial",
    description: "Broader dialer management for growing call-center operations.",
    monthlyPrice: 80,
    yearlyPrice: 960,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Performance tuning", "Priority support queue"],
    techStack: ["Vicidial", "Asterisk", "Call recording review", "SIP routing"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$80/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Premium Vicidial Management",
    slug: "premium-vicidial-management",
    categorySlug: "vicidial",
    description: "High-touch management for larger Vicidial and call-center operations.",
    monthlyPrice: 100,
    yearlyPrice: 1200,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Advanced routing review", "Priority escalation"],
    techStack: ["Vicidial", "Asterisk", "SIP routing", "QA workflow support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$100/mo",
    serviceType: "communications",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Workflow Starter",
    slug: "workflow-starter",
    categorySlug: "workflows",
    description: "Managed n8n workflow automation with a focused app footprint.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: ["3 integrated apps", ...managedOps, "AI workflow guidance"],
    techStack: ["n8n", "Webhook orchestration", "DeepSeek / OpenAI integration"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Workflow Growth",
    slug: "workflow-growth",
    categorySlug: "workflows",
    description: "Expanded workflow automation with more integrations and revision capacity.",
    monthlyPrice: 75,
    yearlyPrice: 900,
    yearlyDiscountPercent: 0,
    features: ["5 integrated apps", ...managedOps, "Monitoring and revisions"],
    techStack: ["n8n", "Webhook routing", "Vector / AI integrations", "Monitoring"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$75/mo",
    serviceType: "automation",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Workflow Enterprise",
    slug: "workflow-enterprise",
    categorySlug: "workflows",
    description: "Enterprise automation architecture with custom integrations and operational support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom app integrations", "Solution architecture", "Dedicated support"],
    techStack: ["n8n", "Custom APIs", "Queue / event design", "Governed deployment"],
    planType: "enterprise",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "automation",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Clawbot",
    slug: "clawbot",
    categorySlug: "ai-solutions",
    description: "Deploy and manage Clawbot-based AI workflows and customer-facing automation.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Managed rollout", "Prompt operations support", "Business automation advisory"],
    techStack: ["Clawbot", "Prompt operations", "Workflow integrations"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "DeepSeek API Access",
    slug: "deepseek-api-access",
    categorySlug: "ai-solutions",
    description: "Managed DeepSeek API access, guardrails, and implementation support.",
    monthlyPrice: 120,
    yearlyPrice: 1440,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Usage guidance", "Integration support"],
    techStack: ["DeepSeek API", "Usage policy controls", "Integration support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$120/mo",
    serviceType: "ai",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Open-Source DeepSeek Services",
    slug: "open-source-deepseek-services",
    categorySlug: "ai-solutions",
    description: "Managed open-source DeepSeek deployment and private model service support.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Model hosting guidance", "Ops and scaling support", "Custom deployment"],
    techStack: ["Open-source DeepSeek", "vLLM / Ollama", "Private deployment controls"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "ai",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Managed Support Basic",
    slug: "managed-support-basic",
    categorySlug: "development-support",
    description: "Recurring support coverage for operations teams needing hands-on technical help.",
    monthlyPrice: 25,
    yearlyPrice: 300,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Monthly support allocation", "Ticket support"],
    techStack: ["Ticket queue support", "Runbook execution", "Infrastructure troubleshooting"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$25/mo",
    serviceType: "support",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Advanced Development Support",
    slug: "advanced-development-support",
    categorySlug: "development-support",
    description: "Managed implementation and technical support for more complex change requests.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscountPercent: 0,
    features: ["Custom engineering support", "Architecture review", "Priority coordination"],
    techStack: ["Application support", "Release coordination", "Architecture guidance"],
    planType: "custom",
    billingCycles: ["contact_sales"],
    isManaged: true,
    isCustom: true,
    contactSalesOnly: true,
    displayPriceLabel: "Contact sales",
    serviceType: "support",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Basic",
    slug: "cybersecurity-basic",
    categorySlug: "cybersecurity",
    description: "Foundational security hardening and routine monitoring for hosted systems.",
    monthlyPrice: 90,
    yearlyPrice: 972,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Baseline hardening checklist", "Security alert triage"],
    techStack: ["Firewall policy review", "OS hardening", "Fail2Ban / WAF"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$90/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Cybersecurity Premium",
    slug: "cybersecurity-premium",
    categorySlug: "cybersecurity",
    description: "Broader monitoring, response coordination, and managed hardening coverage.",
    monthlyPrice: 170,
    yearlyPrice: 1836,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "WAF tuning", "Incident response coordination", "Monthly posture review"],
    techStack: ["WAF / reverse proxy", "SIEM ingestion", "Patch governance"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$170/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Cybersecurity Platinum",
    slug: "cybersecurity-platinum",
    categorySlug: "cybersecurity",
    description: "Premium managed security operations with faster response and deeper review cadence.",
    monthlyPrice: 280,
    yearlyPrice: 3024,
    yearlyDiscountPercent: 10,
    features: [...managedOps, "Priority incident handling", "Security change planning", "Executive risk summary"],
    techStack: ["WAF", "SIEM", "EDR guidance", "Response playbooks"],
    planType: "standard",
    billingCycles: ["monthly", "yearly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$280/mo",
    serviceType: "security",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Standard Managed CDN",
    slug: "standard-managed-cdn",
    categorySlug: "cdn",
    description: "Essential managed CDN performance for websites that need faster European edge delivery and resilient caching.",
    monthlyPrice: 72,
    yearlyPrice: 864,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Full image optimization", "Custom caching rules", "Built-in DDoS protection", "Up to 2 TB monthly traffic", "14-day trial included"],
    techStack: ["CDN edge caching", "Image optimization", "DDoS protection", "SSL support"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$72/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Premium Managed CDN",
    slug: "premium-managed-cdn",
    categorySlug: "cdn",
    description: "Managed CDN for content-heavy businesses that need priority caching, analytics, and stronger security controls.",
    monthlyPrice: 315,
    yearlyPrice: 3780,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Priority caching", "Real-time analytics", "Full security suite", "10 TB monthly traffic", "14-day trial included"],
    techStack: ["Priority edge caching", "Real-time analytics", "Security controls", "Image optimization"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$315/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Unlimited Managed CDN",
    slug: "unlimited-managed-cdn",
    categorySlug: "cdn",
    description: "Enterprise managed CDN service for high-volume platforms that need unlimited traffic and dedicated support.",
    monthlyPrice: 1798.2,
    yearlyPrice: 21578.4,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "Unlimited domains", "Full optimization suite", "Full DDoS and security suite", "Dedicated support", "Unlimited traffic", "14-day trial included"],
    techStack: ["Enterprise CDN", "Dedicated support", "Advanced security", "Full optimization suite"],
    planType: "enterprise",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$1,798.20/mo",
    serviceType: "edge_delivery",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "250 GB Object Storage",
    slug: "object-storage-250gb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for small backup sets, file sharing, and lightweight media workflows.",
    monthlyPrice: 5.38,
    yearlyPrice: 64.56,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "250 GB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$5.38/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "500 GB Object Storage",
    slug: "object-storage-500gb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for growing media libraries, backups, and application assets.",
    monthlyPrice: 10.76,
    yearlyPrice: 129.12,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "500 GB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$10.76/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "1 TB Object Storage",
    slug: "object-storage-1tb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for production backups, content libraries, and app data.",
    monthlyPrice: 21.53,
    yearlyPrice: 258.36,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "1 TB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$21.53/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "2 TB Object Storage",
    slug: "object-storage-2tb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for larger backup, archive, and media delivery requirements.",
    monthlyPrice: 43.06,
    yearlyPrice: 516.72,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "2 TB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$43.06/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 4,
  },
  {
    name: "5 TB Object Storage",
    slug: "object-storage-5tb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for high-volume file, backup, media, and dataset operations.",
    monthlyPrice: 107.64,
    yearlyPrice: 1291.68,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "5 TB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$107.64/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 5,
  },
  {
    name: "10 TB Object Storage",
    slug: "object-storage-10tb",
    categorySlug: "object-storage",
    description: "Managed S3-compatible object storage for large archives, AI datasets, media repositories, and backup estates.",
    monthlyPrice: 215.28,
    yearlyPrice: 2583.36,
    yearlyDiscountPercent: 0,
    features: [...managedOps, "10 TB storage", "S3-compatible API", "Transfer included", "Triple-replicated objects", "DDoS protection"],
    techStack: ["S3-compatible API", "Web UI management", "ACL and link sharing", "Object replication"],
    planType: "standard",
    billingCycles: ["monthly"],
    isManaged: true,
    isCustom: false,
    contactSalesOnly: false,
    displayPriceLabel: "$215.28/mo",
    serviceType: "object_storage",
    isActive: true,
    sortOrder: 6,
  },
  ...selfHostedAppPlanSeeds,
];

const serverCommerceCategorySlugs = ["vps", "vds"];

const serverRegionAddonTemplates = [
  {
    name: "European Union",
    optionCode: "region-eu",
    description: "Low-latency European deployment region.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 10,
  },
  {
    name: "United States (West)",
    optionCode: "region-us-west",
    description: "West coast region for American traffic routing.",
    monthlyPrice: 2.2,
    yearlyPrice: 26.4,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 20,
  },
  {
    name: "Asia (Singapore)",
    optionCode: "region-asia-singapore",
    description: "APAC-friendly region with strong Southeast Asia coverage.",
    monthlyPrice: 4.4,
    yearlyPrice: 52.8,
    addonType: "region",
    selectionMode: "single",
    sortOrder: 30,
  },
];

const serverStorageAddonTemplates = [
  {
    name: "SSD",
    optionCode: "storage-ssd",
    description: "General-purpose SSD storage with a generous included base allocation.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 200,
    pricePerUnitMonthly: 0.012,
    pricePerUnitYearly: 0.144,
    unitLabel: "GB",
    minQuantity: 200,
    quantityStep: 50,
    sortOrder: 40,
  },
  {
    name: "NVMe",
    optionCode: "storage-nvme",
    description: "Higher-throughput NVMe storage for workloads that need faster I/O.",
    addonType: "storage",
    selectionMode: "single",
    monthlyPrice: 0,
    yearlyPrice: 0,
    includedQuantity: 100,
    pricePerUnitMonthly: 0.0315,
    pricePerUnitYearly: 0.378,
    unitLabel: "GB",
    minQuantity: 100,
    quantityStep: 50,
    sortOrder: 50,
  },
];

const serverImageAddonTemplates = [
  {
    name: "Ubuntu",
    optionCode: "image-ubuntu",
    description: "Ubuntu LTS server image.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 60,
  },
  {
    name: "Custom Images",
    optionCode: "image-custom",
    description: "Bring a prepared custom image for deployment.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 70,
  },
  {
    name: "Windows Server",
    optionCode: "image-windows-server",
    description: "Licensed Windows Server image.",
    monthlyPrice: 19.1,
    yearlyPrice: 229.2,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 80,
  },
  {
    name: "cPanel",
    optionCode: "image-cpanel",
    description: "cPanel image with the required management licensing.",
    monthlyPrice: 27.5,
    yearlyPrice: 330,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 90,
  },
  {
    name: "RHEL Variants",
    optionCode: "image-rhel",
    description: "RHEL-compatible variants for enterprise-focused deployments.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 100,
  },
  {
    name: "Plesk + Linux",
    optionCode: "image-plesk-linux",
    description: "Plesk on Linux with the required control-panel licensing.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "image",
    selectionMode: "single",
    sortOrder: 110,
  },
];

export const addonSeeds = [
  {
    name: "Priority Escalation",
    categorySlug: "vps",
    description: "Faster response targets and dedicated operational escalation.",
    monthlyPrice: 20,
    yearlyPrice: 240,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-priority-escalation",
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vps",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Additional IPv4 Address",
    categorySlug: "vds",
    description: "Add one extra public IPv4 address to the managed server.",
    monthlyPrice: 4.5,
    yearlyPrice: 54,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-ipv4",
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Extra Workflow Revision Pack",
    categorySlug: "workflows",
    description: "Additional workflow refinement and optimization hours.",
    monthlyPrice: 15,
    yearlyPrice: 180,
    addonType: "feature",
    selectionMode: "multi",
    optionCode: "feature-extra-workflow-revisions",
    isActive: true,
    sortOrder: 1,
  },
  ...serverCommerceCategorySlugs.flatMap((categorySlug) =>
    [...serverRegionAddonTemplates, ...serverStorageAddonTemplates, ...serverImageAddonTemplates].map((addon) => ({
      ...addon,
      categorySlug,
      isActive: true,
    })),
  ),
];

export const serviceMarketingContent = {
  vps: {
    headline: "Managed VPS for businesses that want hosting without operational overhead.",
    body: "Every VPS plan is operated by the ElevenOrbits team with monitoring, maintenance, and support built in.",
  },
  vds: {
    headline: "Managed VDS with dedicated resources and operational ownership.",
    body: "Use VDS when you need stronger resource isolation while keeping infrastructure management off your team.",
  },
  "ai-servers": {
    headline: "AI-ready infrastructure with managed deployment and support.",
    body: "Run inference or private-model workloads on managed compute while ElevenOrbits operates the platform.",
  },
  vicidial: {
    headline: "Vicidial management subscriptions for reliable call-center operations.",
    body: "We handle updates, tuning, SIP coordination, and support workflows so your agents stay focused.",
  },
  workflows: {
    headline: "Workflow automation on n8n with integrated AI services.",
    body: "Build dependable automations with managed integration, orchestration, and AI-assisted delivery.",
  },
  "ai-solutions": {
    headline: "AI products and managed APIs delivered with operational support.",
    body: "Use ElevenOrbits for managed AI product rollout, prompt operations, and private-model support.",
  },
  "development-support": {
    headline: "Managed support coverage for teams that need technical execution help.",
    body: "Use recurring support plans for implementation help, issue handling, and change coordination.",
  },
  cybersecurity: {
    headline: "Managed cybersecurity services for hosting, applications, and operational risk.",
    body: "Protect hosted systems with managed hardening, monitoring, incident coordination, and security reviews.",
  },
  cdn: {
    headline: "Managed CDN for fast, resilient content delivery across Europe.",
    body: "Use managed CDN packages for caching, image optimization, DDoS protection, SSL coordination, and low-latency delivery for ecommerce and content-heavy sites.",
  },
  "object-storage": {
    headline: "Managed S3-compatible object storage with predictable monthly tiers.",
    body: "Store backups, media, archives, and AI datasets with managed setup support, S3-compatible access, redundancy, ACL guidance, and migration help.",
  },
  "hermes-ai-hosting": {
    headline: "Managed Hermes AI VPS hosting for private always-on agents.",
    body: "Run a self-hosted Hermes Agent with memory across sessions, private data control, tool integrations, app handoff, and managed VPS operations.",
  },
  "openclaw-hosting": {
    headline: "Managed OpenClaw VPS hosting for AI assistants that act for you.",
    body: "Host OpenClaw on a managed VPS for messaging integrations, automation, tool use, private data control, and customer portal access handoff.",
  },
  "nextcloud-hosting": {
    headline: "Managed Nextcloud hosting for private sync, sharing, backup, and collaboration.",
    body: "Launch a self-hosted Nextcloud private cloud with managed VPS resources, app handoff, unlimited users, data control, and support.",
  },
};
